export const VERB_DATA = {
  "قَالَ": { rank: 1000, meaning: "to say" },
  "كَانَ": { rank: 2010, meaning: "they used to" },
  "ءَامَنَ": { rank: 2003, meaning: "to believe" },
  "عَلِمَ": { rank: 1000, meaning: "to know" },
  "جَعَلَ": { rank: 2019, meaning: "to put" },
  "كَفَرَ": { rank: 2006, meaning: "to disbelieve" },
  "جَآءَ": { rank: 2071, meaning: "to come" },
  "عَمِلَ": { rank: 2025, meaning: "to do" },
  "رَءَا": { rank: 2055, meaning: "to see" },
  "آتَى": { rank: 2043, meaning: "to give" },
  "أَتَى": { rank: 2023, meaning: "to produce" },
  "شَآءَ": { rank: 2020, meaning: "to will" },
  "خَلَقَ": { rank: 2021, meaning: "to create" },
  "أَنزَلَ": { rank: 2004, meaning: "to send" },
  "كَذَّبَ": { rank: 2039, meaning: "to deny" },
  "دَعَا": { rank: 2023, meaning: "to call" },
  "ٱتَّقَىٰ": { rank: 2021, meaning: "to become righteous" },
  "هَدَى": { rank: 1006, meaning: "to guide" },
  "أَرَادَ": { rank: 2026, meaning: "to intend" },
  "ٱتَّبَعَ": { rank: 2102, meaning: "to follow" },
  "أَرْسَلَ": { rank: 2119, meaning: "to send" },
  "أَخَذَ": { rank: 2048, meaning: "to take" },
  "ٱتَّخَذَ": { rank: 2051, meaning: "to take" },
  "عَبَدَ": { rank: 1005, meaning: "to worship" },
  "ظَلَمَ": { rank: 2054, meaning: "to wrong" },
  "سَأَلَ": { rank: 2061, meaning: "to ask for" },
  "وَجَدَ": { rank: 2096, meaning: "to surely find" },
  "أَخْرَجَ": { rank: 2022, meaning: "to bring forth" },
  "أَكَلَ": { rank: 2035, meaning: "to et" },
  "لَّيْسَ": { rank: 2113, meaning: "Not" },
  "فَعَلَ": { rank: 2024, meaning: "to do" },
  "نَّظَرَ": { rank: 2050, meaning: "to look" },
  "ذَكَرَ": { rank: 2040, meaning: "to remember" },
  "خَافَ": { rank: 2182, meaning: "to fear" },
  "قَتَلَ": { rank: 2054, meaning: "to kill" },
  "رَجَعَ": { rank: 2018, meaning: "to return" },
  "سَمِعَ": { rank: 2075, meaning: "to hear" },
  "تَوَلَّىٰ": { rank: 2064, meaning: "to turn away" },
  "أَمَرَ": { rank: 2027, meaning: "to order" },
  "دَخَلَ": { rank: 1000, meaning: "to enter" },
  "جَزَىٰ": { rank: 2048, meaning: "to avail" },
  "أَطَاعَ": { rank: 2285, meaning: "to obey" },
  "أَوْحَىٰٓ": { rank: 3044, meaning: "to reveal" },
  "أَلْقَىٰٓ": { rank: 2195, meaning: "to throw" },
  "أَشْرَكَ": { rank: 2096, meaning: "to associate" },
  "وَعَدَ": { rank: 1000, meaning: "to promise" },
  "أَنفَقَ": { rank: 2003, meaning: "to send" },
  "غَفَرَ": { rank: 2058, meaning: "to forgive" },
  "أَحْبَبْ": { rank: 2165, meaning: "to love" },
  "أَصَابَ": { rank: 2156, meaning: "to strike" },
  "أَضَلَّ": { rank: 2026, meaning: "to go astray" },
  "تَابَ": { rank: 2037, meaning: "so repent" },
  "نَزَّلَ": { rank: 2023, meaning: "to reveal" },
  "كَسَبَ": { rank: 2079, meaning: "to earn" },
  "رَزَقَ": { rank: 2003, meaning: "to provide" },
  "تَلَىٰ": { rank: 2044, meaning: "to recite" },
  "نَصَرَ": { rank: 2048, meaning: "to help" },
  "قَضَىٰٓ": { rank: 2117, meaning: "to decree" },
  "صَبَرَ": { rank: 2061, meaning: "to endure" },
  "جَرَيْ": { rank: 2025, meaning: "to flow" },
  "مَسَّ": { rank: 2080, meaning: "to teach" },
  "ضَرَبَ": { rank: 2026, meaning: "to set forth" },
  "أَقَامَ": { rank: 2003, meaning: "to establish" },
  "قَٰتَلَ": { rank: 2190, meaning: "to fight" },
  "ضَلَّ": { rank: 2108, meaning: "to go astray" },
  "خَرَجَ": { rank: 2074, meaning: "to come out" },
  "بَعَثَ": { rank: 2056, meaning: "to revive" },
  "تَذَكَّرَ": { rank: 2221, meaning: "to take heed" },
  "أَحْيَا": { rank: 2028, meaning: "to give life" },
  "أَهْلَكَ": { rank: 2205, meaning: "to destroy" },
  "ٱفْتَرَىٰ": { rank: 3024, meaning: "to invent" },
  "كَتَبَ": { rank: 2079, meaning: "to write" },
  "عَقَلُ": { rank: 2044, meaning: "to reason" },
  "زَادَ": { rank: 2010, meaning: "to increase" },
  "ظَنَّ": { rank: 2046, meaning: "to believe" },
  "نَبَّأَ": { rank: 3015, meaning: "to inform" },
  "شَكَرَ": { rank: 2052, meaning: "to be grateful" },
  "حَكَمَ": { rank: 2113, meaning: "to judge" },
  "يَذَرَ": { rank: 2234, meaning: "to leave behind" },
  "مَلَكَتْ": { rank: 4003, meaning: "to posses" },
  "حَسِبَ": { rank: 2214, meaning: "to think" },
  "شَهِدَ": { rank: 2084, meaning: "to witness" },
  "نَادَىٰ": { rank: 3039, meaning: "to call" },
  "أَنذَرَ": { rank: 2006, meaning: "to warn" },
  "سَبَّحَ": { rank: 2030, meaning: "to glorify" },
  "أُدْخِلَ": { rank: 3185, meaning: "to admit" },
  "ٱسْتَطَاعَ": { rank: 2217, meaning: "to be able" },
  "حَمَلَ": { rank: 2248, meaning: "to carry" },
  "عَلَّمَ": { rank: 1000, meaning: "to teach" },
  "عَذَّبَ": { rank: 2284, meaning: "to punish" },
  "ٱسْتَكْبَرَ": { rank: 2034, meaning: "to be arrogant" },
  "بِئْسَ": { rank: 2090, meaning: "to be evil" },
  "تَرَكَ": { rank: 2017, meaning: "to leave" },
  "ٱسْتَغْفَرَ": { rank: 2199, meaning: "to ask for forgiveness" },
  "بَلَغَ": { rank: 2196, meaning: "to reach" },
  "تَوَكَّلْ": { rank: 1000, meaning: "to put trust" },
  "خَشِىَ": { rank: 2150, meaning: "to fear" },
  "ٱهْتَدَىٰ": { rank: 2053, meaning: "to be guided" },
  "أَرَيْ": { rank: 2073, meaning: "to show" },
  "حَرَّمَ": { rank: 2173, meaning: "to forbid" },
  "مَّاتَ": { rank: 2132, meaning: "to die" },
  "رَّضِىَ": { rank: 2120, meaning: "to be pleased" },
  "بُشِّرَ": { rank: 2025, meaning: "to give good news" },
  "يَحْزُن": { rank: 2038, meaning: "to grieve" },
  "نَجَّىٰ": { rank: 2049, meaning: "to save" },
  "حَشَرَ": { rank: 2203, meaning: "to gather" },
  "صَدَّ": { rank: 3099, meaning: "to hinder" },
  "ذَاقُ": { rank: 3106, meaning: "to taste" },
  "رَدَّ": { rank: 2085, meaning: "to be sent back" },
  "ٱخْتَلَفَ": { rank: 2113, meaning: "to differ" },
  "ٱسْتَوَىٰٓ": { rank: 2029, meaning: "to turn" },
  "ذَهَبَ": { rank: 2017, meaning: "to take away" },
  "بَيَّنُ": { rank: 2068, meaning: "to make clear" },
  "سَجَدَ": { rank: 2034, meaning: "to prostrate" },
  "نَسِىَ": { rank: 2044, meaning: "to forget" },
  "ٱبْتَغَىٰ": { rank: 2187, meaning: "to seek" },
  "قَامَ": { rank: 2020, meaning: "to stand still" },
  "نَهَىٰ": { rank: 3104, meaning: "to forbid" },
  "أَعْرَضَ": { rank: 4016, meaning: "to turn away" },
  "كَفَىٰ": { rank: 2137, meaning: "to be sufficient" },
  "نَفَعَ": { rank: 2102, meaning: "to profit" },
  "وَلَّىٰ": { rank: 2115, meaning: "to turn" },
  "لَبِثَ": { rank: 2259, meaning: "to remain" },
  "سَآءَ": { rank: 3120, meaning: "to grieve" },
  "عَسَى": { rank: 2216, meaning: "perhaps" },
  "أَبْصَرَ": { rank: 2017, meaning: "to see" },
  "أَغْنَتْ": { rank: 3010, meaning: "to avail" },
  "أَصْبَحَ": { rank: 3103, meaning: "to become" },
  "ٱسْتَجَابَ": { rank: 2186, meaning: "to let them respond" },
  "أَصْلَحَ": { rank: 2160, meaning: "to reform" },
  "رَّحِمَ": { rank: 2286, meaning: "to have mercy" },
  "قَدَّمَ": { rank: 2095, meaning: "to offer" },
  "جَٰهَدَ": { rank: 2218, meaning: "to strive" },
  "عَصَا": { rank: 2061, meaning: "to disobey" },
  "عَفَا": { rank: 2052, meaning: "to forgive" },
  "أَفْلَحَ": { rank: 2189, meaning: "to be successful" },
  "زَيَّنَ": { rank: 2212, meaning: "to be beautiful" },
  "يَشْعُرُ": { rank: 2009, meaning: "to realize" },
  "بَغَىٰ": { rank: 3083, meaning: "to seek" },
  "خَلَا": { rank: 2014, meaning: "to be alone" },
  "جَٰدَلُ": { rank: 4107, meaning: "to argue" },
  "قَدَرَ": { rank: 2264, meaning: "to have control" },
  "تَوَفَّىٰ": { rank: 2234, meaning: "to pass away" },
  "كَادَ": { rank: 2020, meaning: "almost" },
  "أَنجَىٰ": { rank: 2050, meaning: "to save" },
  "فَتَنُ": { rank: 4101, meaning: "to harm" },
  "بَدَّلَ": { rank: 2059, meaning: "to change" },
  "لَعَنَ": { rank: 2088, meaning: "to curse" },
  "أَذِنَ": { rank: 2279, meaning: "to be informed" },
  "رَفَعَ": { rank: 2063, meaning: "to raise" },
  "أَسْلَمَ": { rank: 2112, meaning: "to submit" },
  "سَخَّرَ": { rank: 13002, meaning: "to be subjected" },
  "أَذَاقَ": { rank: 6065, meaning: "to taste" },
  "مَكَرَ": { rank: 3054, meaning: "to schemed" },
  "يَرْجُوا۟": { rank: 2218, meaning: "to hope" },
  "جَمَعَ": { rank: 3025, meaning: "to gather" },
  "وَهَبَ": { rank: 3008, meaning: "to grant" },
  "ٱشْتَرَىٰ": { rank: 2016, meaning: "to bring" },
  "أَمَاتَ": { rank: 2028, meaning: "to cause to die" },
  "كَتَمَ": { rank: 2033, meaning: "to conceal" },
  "أَحْسَنَ": { rank: 2195, meaning: "to be good" },
  "ٱسْتُهْزِئَ": { rank: 2015, meaning: "to mock" },
  "مَّشَ": { rank: 2020, meaning: "to walk" },
  "وَضَعَ": { rank: 3036, meaning: "to deliver" },
  "أَعَدَّ": { rank: 2024, meaning: "to be prepare" },
  "أَنشَأَ": { rank: 6006, meaning: "to initiate" },
  "تَعَٰلَىٰ": { rank: 6100, meaning: "to be exalted" },
  "عَرَفَ": { rank: 2089, meaning: "to recognize" },
  "أَمِنَ": { rank: 2196, meaning: "to be secure" },
  "بَلَوْ": { rank: 2155, meaning: "to test" },
  "أَقْسَمُ": { rank: 5053, meaning: "to swear" },
  "حَقَّ": { rank: 7030, meaning: "to deserve" },
  "سَعَىٰ": { rank: 2114, meaning: "to strive" },
  "كَلَّمَ": { rank: 2118, meaning: "to speak" },
  "سَبَقَ": { rank: 7080, meaning: "has preceded you" },
  "أَحَلَّ": { rank: 2187, meaning: "to permit" },
  "قَصَّ": { rank: 4164, meaning: "to mention" },
  "ٱسْتَعْجَلَ": { rank: 6057, meaning: "to seek to hasten" },
  "يَضُرَّ": { rank: 2102, meaning: "to harm" },
  "يَفْقَهُ": { rank: 4078, meaning: "to understand" },
  "نَفَخَ": { rank: 3049, meaning: "to breathe" },
  "ذُكِّرَ": { rank: 2282, meaning: "to remind" },
  "أَوْفَىٰ": { rank: 2040, meaning: "to fulfill" },
  "أُعِيدُ": { rank: 10004, meaning: "to repeat" },
  "أُخْفِىَ": { rank: 2271, meaning: "to keep a sercet" },
  "نِعْمَ": { rank: 2271, meaning: "to be good" },
  "وَفَّىٰٓ": { rank: 2272, meaning: "to be paid in full" },
  "تَبَيَّنَ": { rank: 2109, meaning: "to be clear" },
  "مَّتَّعْ": { rank: 2126, meaning: "to grant enjoyment" },
  "عَادَ": { rank: 2275, meaning: "to repeat" },
  "أَسَرَّ": { rank: 2077, meaning: "to conceal" },
  "أَمْسَكَ": { rank: 2231, meaning: "to retain" },
  "وَدَّ": { rank: 2096, meaning: "to love" },
  "يَتَفَكَّرُ": { rank: 2219, meaning: "to ponder" },
  "أُغْرِقُ": { rank: 2050, meaning: "to drown" },
  "أَنْعَمَ": { rank: 1007, meaning: "to bestow favour" },
  "فَضَّلَ": { rank: 2047, meaning: "to prefer" },
  "كَرِهَ": { rank: 2216, meaning: "to dislike" },
  "ٱنقَلَبَ": { rank: 2143, meaning: "to turn back" },
  "أَدْرَىٰ": { rank: 10016, meaning: "to make someone know" },
  "فَصَّلَ": { rank: 6055, meaning: "to explain" },
  "أَحَاطَ": { rank: 2081, meaning: "to surround" },
  "قَدَّرَ": { rank: 10005, meaning: "to determine" },
  "سَارَ": { rank: 3137, meaning: "to travel" },
  "هَاجَرَ": { rank: 2218, meaning: "to emigrate" },
  "فَتَحَ": { rank: 2076, meaning: "to open" },
  "مَنَّ": { rank: 3164, meaning: "to bestow favour" },
  "قَرَأَ": { rank: 7204, meaning: "to recite" },
  "خَسِرَ": { rank: 4119, meaning: "to lose" },
  "أُفِكَ": { rank: 5075, meaning: "to be delusional" },
  "ٱنتَهَىٰ": { rank: 2192, meaning: "to cease" },
  "بَسَطَ": { rank: 2245, meaning: "to grant in abundance" },
  "ٱسْتَمَعَ": { rank: 6025, meaning: "to listen" },
  "أَنۢبَتَ": { rank: 2061, meaning: "to grow" },
  "وَقَىٰ": { rank: 2201, meaning: "to save" },
  "أَتَمَّ": { rank: 2124, meaning: "to fulfill" },
  "فَرِحَ": { rank: 3120, meaning: "to rejoice" },
  "غَلَبُ": { rank: 2249, meaning: "to overcome" },
  "صَنَعُ": { rank: 5014, meaning: "to do" },
  "شَرِبَ": { rank: 2060, meaning: "to drink" },
  "ٱعْتَدَىٰ": { rank: 2061, meaning: "to transgress" },
  "صَدَقَ": { rank: 2177, meaning: "to be true" },
  "وَعَظْ": { rank: 2231, meaning: "to instruct" },
  "غَرَّ": { rank: 3024, meaning: "to decieve" },
  "أَغْنَىٰ": { rank: 7048, meaning: "to avail" },
  "أَخَّرَ": { rank: 4077, meaning: "to postpone" },
  "أُوذِىَ": { rank: 3195, meaning: "to harm" },
  "أَتْبَعَ": { rank: 2262, meaning: "to follow" },
  "أَفْسَدُ": { rank: 2011, meaning: "to spread corruption" },
  "يُبْدِىَ": { rank: 2033, meaning: "to reveal" },
  "سَكَنَ": { rank: 2035, meaning: "to dwell" },
  "لَقُ": { rank: 2014, meaning: "to meet" },
  "عَدَلَ": { rank: 4003, meaning: "to do justice" },
  "أَعْتَدَتْ": { rank: 4018, meaning: "to prepare" },
  "حَلَلْ": { rank: 2228, meaning: "to be lawful" },
  "نَكَحَ": { rank: 2221, meaning: "to marry" },
  "كَشَفَ": { rank: 6041, meaning: "to uncover" },
  "كَفَّرَ": { rank: 2271, meaning: "to cover" },
  "أَخْلَفُ": { rank: 2080, meaning: "to break" },
  "صَرَفَ": { rank: 3152, meaning: "to divert" },
  "وَرِثَ": { rank: 4011, meaning: "to inherit" },
  "تَرَبَّصْ": { rank: 2228, meaning: "to wait" },
  "أَسْمَعَ": { rank: 8023, meaning: "to make someone hear" },
  "زَعَمَ": { rank: 4060, meaning: "to claim" },
  "غَشِيَ": { rank: 3154, meaning: "to overcome" },
  "سَوَّىٰ": { rank: 2029, meaning: "to fashion" },
  "أَبَى": { rank: 2034, meaning: "to refuse" },
  "مَدَّ": { rank: 2015, meaning: "to prolong" },
  "أَطْعَمَ": { rank: 5089, meaning: "to feed" },
  "يَصِفُ": { rank: 6100, meaning: "to attribute" },
  "مَكَّ": { rank: 6006, meaning: "to establish" },
  "يَصْلَى": { rank: 4010, meaning: "to burn" },
  "سَلَكَ": { rank: 15012, meaning: "to let someone enter" },
  "يُنظَرُ": { rank: 2162, meaning: "to be reprieved" },
  "حَبِطَ": { rank: 2217, meaning: "to become worthless" },
  "مَّنَعَ": { rank: 2114, meaning: "to prevent" },
  "ٱصْطَفَىٰ": { rank: 2130, meaning: "to chase" },
  "أَعْلَن": { rank: 2077, meaning: "to declare" },
  "وَقَعَ": { rank: 4100, meaning: "to become incumbent" },
  "قُطِعَ": { rank: 2027, meaning: "to cut" },
  "ٱسْتَْٔذَنَ": { rank: 9044, meaning: "to seek permission" },
  "تَدْرِى": { rank: 4011, meaning: "to know" },
  "خَرَّ": { rank: 7143, meaning: "to fall down" },
  "قَطَّعَ": { rank: 5033, meaning: "to cut off" },
  "قَعَدَ": { rank: 3168, meaning: "to sit" },
  "صَلَّىٰ": { rank: 3039, meaning: "to pray" },
  "يَحْذَرُ": { rank: 2235, meaning: "to be beware" },
  "بَدَأَ": { rank: 7029, meaning: "to originate" },
  "حَآجَّ": { rank: 2076, meaning: "to argue with" },
  "جَحَدُ": { rank: 6033, meaning: "to reject" },
  "أَوْرَثَ": { rank: 7043, meaning: "to inherit" },
  "طَغَىٰ": { rank: 11112, meaning: "to transgress" },
  "سَقَىٰ": { rank: 2071, meaning: "to water" },
  "زَكَّىٰ": { rank: 2129, meaning: "to purify" },
  "أَخْزَيْ": { rank: 3192, meaning: "to disgrace" },
  "حَلَفْ": { rank: 4062, meaning: "to swear" },
  "يُوقِنُ": { rank: 2004, meaning: "to firmly believe" },
  "يَقْرَبُ": { rank: 2035, meaning: "to approach" },
  "هَادُ": { rank: 2062, meaning: "to became Jews" },
  "بَدَا": { rank: 3118, meaning: "to become apparent" },
  "كَذَبَ": { rank: 2010, meaning: "to lie" },
  "يَسَّرَ": { rank: 19097, meaning: "to make it easy" },
  "سَخِرَ": { rank: 2212, meaning: "to ridicule" },
  "طَبَعَ": { rank: 4155, meaning: "to set a seal" },
  "عَرَضَ": { rank: 2031, meaning: "to display" },
  "أَذْهَبَ": { rank: 4133, meaning: "to take away" },
  "بَنَىٰ": { rank: 9110, meaning: "to build" },
  "أَعْجَبَ": { rank: 2204, meaning: "to please" },
  "عَٰهَدَ": { rank: 2100, meaning: "to take" },
  "وَصَّىٰ": { rank: 2132, meaning: "to enjoin" },
  "أَنَابَ": { rank: 11088, meaning: "to turn" },
  "يَنَالُ": { rank: 2124, meaning: "to reach" },
  "لَبَسْ": { rank: 2042, meaning: "to mix" },
  "تَمَتَّعَ": { rank: 2196, meaning: "to take advantage" },
  "يَصِلُ": { rank: 2027, meaning: "to join" },
  "تَقَبَّلَ": { rank: 2127, meaning: "to accept" },
  "ثَبَّتْ": { rank: 2250, meaning: "to make firm" },
  "حَاقَ": { rank: 6010, meaning: "to surround" },
  "نَزَعَ": { rank: 3026, meaning: "to take away" },
  "أَمَدَّ": { rank: 3124, meaning: "to reinforce" },
  "يُولِجُ": { rank: 3027, meaning: "to cause to enter" },
  "صَرَّفْ": { rank: 6046, meaning: "to explain" },
  "صَدَّقَ": { rank: 28034, meaning: "to confirm" },
  "ٱسْتَقَٰمُ": { rank: 9007, meaning: "to be upright" },
  "ظَهَرَ": { rank: 6151, meaning: "to be apparent" },
  "بَخِلَ": { rank: 3180, meaning: "to withhold" },
  "مَرَّ": { rank: 2259, meaning: "to pass" },
  "ٱجْتَبَىٰ": { rank: 3179, meaning: "to choose" },
  "أَضَاعُ": { rank: 2143, meaning: "to go waste" },
  "طَلَّقَ": { rank: 2230, meaning: "to divorces" },
  "عُذْ": { rank: 2067, meaning: "to seek refuge" },
  "نَبَذَ": { rank: 2100, meaning: "to throw away" },
  "فَسَقَ": { rank: 2059, meaning: "to defiantly disobey" },
  "فَطَرَ": { rank: 6079, meaning: "to create" },
  "أَحْصَىٰ": { rank: 14034, meaning: "to count them" },
  "أَقْبَلَ": { rank: 12071, meaning: "to turn towards" },
  "يُؤَاخِذُ": { rank: 2225, meaning: "to sieze" },
  "ءَاوَىٰٓ": { rank: 8026, meaning: "to shelter" },
  "ٱنطَلَقَ": { rank: 18071, meaning: "to set out" },
  "طَهَّرَ": { rank: 2125, meaning: "to purify" },
  "ظَلَّ": { rank: 15014, meaning: "to continue" },
  "ٱطْمَأَنَّ": { rank: 2260, meaning: "to satisfy" },
  "قَذَفَ": { rank: 20039, meaning: "to cast him" },
  "يَسْتَحْىِۦٓ": { rank: 2026, meaning: "to be ashamed" },
  "يَنطِقُ": { rank: 21063, meaning: "to speak" },
  "فَرَّقُ": { rank: 2102, meaning: "to causes separation" },
  "فَرَضَ": { rank: 2197, meaning: "to undertake" },
  "يَلْعَبْ": { rank: 6091, meaning: "to play" },
  "يَقْبَلُ": { rank: 2048, meaning: "to accepted" },
  "رَمَىٰ": { rank: 4112, meaning: "to throw" },
  "رَكِبَ": { rank: 11041, meaning: "to embark" },
  "تَبِعَ": { rank: 2038, meaning: "to follow" },
  "خَاضُ": { rank: 4140, meaning: "to engage" },
  "وَلَدَ": { rank: 11072, meaning: "to bear a child" },
  "ٱجْتَنَبُ": { rank: 4031, meaning: "to avoid" },
  "يُضَٰعِفُ": { rank: 2245, meaning: "to multiply" },
  "ٱرْتَابَ": { rank: 2282, meaning: "to have doubt" },
  "أَيَّدَ": { rank: 2087, meaning: "to support" },
  "يَتَسَآءَلُ": { rank: 4001, meaning: "to ask" },
  "يُسَٰرِعُ": { rank: 3114, meaning: "to hasten" },
  "أَمْلَىٰ": { rank: 3178, meaning: "to give respite" },
  "تَبَارَكَ": { rank: 7054, meaning: "to bless" },
  "تَفَرَّقَ": { rank: 3103, meaning: "to divide" },
  "يَطْمَعُ": { rank: 2075, meaning: "to hope" },
  "دَمَّرَ": { rank: 7137, meaning: "to destroy" },
  "يَئِسَ": { rank: 5003, meaning: "to dispair" },
  "طَافَ": { rank: 37045, meaning: "to circulate" },
  "كَفَّ": { rank: 4077, meaning: "to restrain" },
  "كِيدُ": { rank: 7195, meaning: "to plot against" },
  "خَفَّفَ": { rank: 2086, meaning: "to lighten" },
  "رَٰوَدُ": { rank: 12023, meaning: "to seduce" },
  "زَالَت": { rank: 2217, meaning: "to cease" },
  "هَوَىٰ": { rank: 2087, meaning: "to desire" },
  "هَمَّ": { rank: 3122, meaning: "to incline" },
  "عَجِبُ": { rank: 7063, meaning: "to wonder" },
  "سَمَّىٰ": { rank: 3036, meaning: "to named" },
  "نَفَرَ": { rank: 4071, meaning: "to advance" },
  "خَسَفَ": { rank: 16045, meaning: "to cave" },
  "كَبُرَ": { rank: 4006, meaning: "to grow up" },
  "أُجِيبَت": { rank: 2186, meaning: "to respond" },
  "تَعَالَ": { rank: 3061, meaning: "to come" },
  "ٱزْدَادُ": { rank: 3090, meaning: "to increase" },
  "ٱسْتَضْعَفُ": { rank: 7075, meaning: "to oppress" },
  "ٱرْتَدَّ": { rank: 2217, meaning: "to turns away" },
  "ٱشْتَهَتْ": { rank: 16057, meaning: "to desire" },
  "تَزَكَّىٰ": { rank: 20076, meaning: "to purifies oneself" },
  "أَظْهَرَ": { rank: 9033, meaning: "to manifest" },
  "أَعْطَىٰ": { rank: 9029, meaning: "to pay" },
  "أَسْقَيْ": { rank: 15022, meaning: "to give to drink" },
  "ٱبْتَلَىٰٓ": { rank: 2124, meaning: "to try" },
  "يَهْبِطُ": { rank: 2036, meaning: "to go down" },
  "بَٰرَكَ": { rank: 7137, meaning: "to bless" },
  "ٱخْتَصَمُ": { rank: 3044, meaning: "to dispute" },
  "أَغْوَيْ": { rank: 7016, meaning: "to send astray" },
  "يَنتَظِرُ": { rank: 6158, meaning: "to wait" },
  "عَمِىَ": { rank: 5071, meaning: "to become blind" },
  "أَفَاضَ": { rank: 2198, meaning: "to depart" },
  "أَنسَىٰ": { rank: 2106, meaning: "to cause it to be forgotten" },
  "ٱضْطُرَّ": { rank: 2126, meaning: "to force" },
  "يَزِرُ": { rank: 6031, meaning: "to bear" },
  "يُنقَصُ": { rank: 9004, meaning: "to fail you" },
  "أَشْهَدَ": { rank: 2204, meaning: "to witness" },
  "يَسْتَبْشِرُ": { rank: 3170, meaning: "to receive good tidings" },
  "ضَحِكَتْ": { rank: 9082, meaning: "to laugh" },
  "تَنَزَّلَتْ": { rank: 19064, meaning: "to descend" },
  "تَنَٰزَعُ": { rank: 3152, meaning: "to fall into dispute" },
  "عَدَّ": { rank: 14034, meaning: "to count" },
  "ضَاقَ": { rank: 9025, meaning: "to become narrow" },
  "ٱعْتَزَلَ": { rank: 2222, meaning: "to keep away (from)" },
  "شَآقُّ": { rank: 4115, meaning: "to oppose" },
  "أُمْطِرَتْ": { rank: 7084, meaning: "to shower" },
  "دَامُ": { rank: 3075, meaning: "to keep constantly" },
  "ٱلْتَقَى": { rank: 3013, meaning: "to meet" },
  "طَّلَعَ": { rank: 5013, meaning: "to discover" },
  "سِيقَ": { rank: 7057, meaning: "to drive" },
  "يَعْمَهُ": { rank: 2015, meaning: "to wander blindly" },
  "دَلَّ": { rank: 7022, meaning: "to make fall" },
  "ٱنتَصَرَ": { rank: 26093, meaning: "to help themselves" },
  "ٱفْتَدَىٰ": { rank: 2229, meaning: "to ransom" },
  "حَىَّ": { rank: 7025, meaning: "to live" },
  "حَفِظَ": { rank: 4034, meaning: "to order to guard" },
  "يُكَلِّفُ": { rank: 2233, meaning: "to burden" },
  "حَضَرَ": { rank: 2133, meaning: "to come" },
  "زَاغَ": { rank: 9117, meaning: "to deviate" },
  "تَصَدَّقَ": { rank: 2280, meaning: "to remit as charity" },
  "بَآءَ": { rank: 2061, meaning: "to drew on oneself" },
  "مُلِئَتْ": { rank: 7018, meaning: "to fill" },
  "بَلَّغْ": { rank: 5067, meaning: "to onvey" },
  "يَتَمَنَّ": { rank: 2094, meaning: "to wish" },
  "سَلَّمَ": { rank: 2233, meaning: "to pay" },
  "نَقَضَتْ": { rank: 2027, meaning: "to break" },
  "يَخْفَىٰ": { rank: 3005, meaning: "to hide" },
  "ثُقِفُ": { rank: 2191, meaning: "to find" },
  "شَدَدْ": { rank: 10088, meaning: "to harden" },
  "يَنۢبَغِى": { rank: 19092, meaning: "to appropriate" },
  "بَوَّأَ": { rank: 3121, meaning: "to post" },
  "نَزَلَ": { rank: 17105, meaning: "to be descended" },
  "يَسْتَأْخِرُ": { rank: 7034, meaning: "to seek to delay" },
  "يَسْتَفْتُ": { rank: 4127, meaning: "to seek your ruling" },
  "أَقْرَضُ": { rank: 2245, meaning: "to lend" },
  "أَسْرَفَ": { rank: 6141, meaning: "to be extravagant" },
  "قَلَّبُ": { rank: 6110, meaning: "to turn" },
  "ٱنتَقَمْ": { rank: 5095, meaning: "to take retribution" },
  "فُجِّرَتْ": { rank: 17091, meaning: "to gush forth" },
  "أَدْرَكَ": { rank: 4078, meaning: "to overtake" },
  "فَرَّتْ": { rank: 26021, meaning: "to flee" },
  "يُجِيرُ": { rank: 9006, meaning: "to grant protection" },
  "ذَرَأَ": { rank: 6136, meaning: "to produce" },
  "ظَٰهَرُ": { rank: 9004, meaning: "to supported" },
  "غَضِبَ": { rank: 4093, meaning: "to send wrath" },
  "يَصْفَحُ": { rank: 2109, meaning: "to overlook" },
  "أَسْرَىٰ": { rank: 11081, meaning: "to travel" },
  "عَهِدَ": { rank: 2125, meaning: "to make a covenant" },
  "عَاقَبَ": { rank: 16126, meaning: "to retaliate" },
  "ٱسْتَمْتَعَ": { rank: 4024, meaning: "to benefit" },
  "نَّكَثَ": { rank: 7135, meaning: "to broke the word" },
  "وَسِعَ": { rank: 2255, meaning: "to extend" },
  "بَايَعْ": { rank: 9111, meaning: "to contract" },
  "لَقَّىٰ": { rank: 25075, meaning: "to met" },
  "زُوِّجَتْ": { rank: 33037, meaning: "to marry" },
  "بَكَتْ": { rank: 9082, meaning: "to weep" },
  "حُمِّلَ": { rank: 2286, meaning: "to lay" },
  "بَثَّ": { rank: 2164, meaning: "to disperse" },
  "بَطَشْ": { rank: 7195, meaning: "to hold" },
  "خَانُ": { rank: 8027, meaning: "to betray" },
  "خَتَمَ": { rank: 2007, meaning: "to set a seal" },
  "خَلَفَ": { rank: 7142, meaning: "to take ones place" },
  "رَجَمْ": { rank: 11091, meaning: "to stone" },
  "تَبَرَّأَ": { rank: 2166, meaning: "to disown" },
  "بَرَزَ": { rank: 2250, meaning: "to go forth" },
  "وَهَنَ": { rank: 3139, meaning: "to weaken" },
  "ذُبِحَ": { rank: 2067, meaning: "to slaughter" },
  "دَفَعْ": { rank: 3167, meaning: "to defend" },
  "يُفْتِي": { rank: 4127, meaning: "to gives the ruling" },
  "يُعَمَّرُ": { rank: 2096, meaning: "to grant a life" },
  "دَرَسُ": { rank: 3079, meaning: "to study" },
  "هَلَكَ": { rank: 4176, meaning: "o die" },
  "آثَرَ": { rank: 12091, meaning: "to prefer" },
  "غَلَّ": { rank: 3161, meaning: "to defraud" },
  "أَسَآءَ": { rank: 17007, meaning: "to do evil" },
  "أَرْضَعَتْ": { rank: 4023, meaning: "to nurse" },
  "ٱقْتَرَبَ": { rank: 7185, meaning: "to come near" },
  "فَرَقْ": { rank: 2050, meaning: "to parted" },
  "فَرَّط": { rank: 6031, meaning: "to neglect" },
  "فَصَلَ": { rank: 2249, meaning: "to set out" },
  "ٱكْتَسَبَ": { rank: 2286, meaning: "to earn" },
  "قَبَضْ": { rank: 2245, meaning: "to withhold" },
  "أَحْصَنَتْ": { rank: 4025, meaning: "to marry" },
  "أَجْرَمُ": { rank: 6124, meaning: "to commit crimes" },
  "قَرَّبَ": { rank: 5027, meaning: "to offer" },
  "ٱنشَقَّ": { rank: 19090, meaning: "to split" },
  "أَثَارُ": { rank: 2071, meaning: "to plough" },
  "أَبْلَغُ": { rank: 7079, meaning: "to conveyed" },
  "ءَانَسَ": { rank: 4006, meaning: "to perceive" },
  "ٱعْتَصَمُ": { rank: 3101, meaning: "to hold firmly" },
  "أَسْكَن": { rank: 14014, meaning: "to dwell" },
  "أُكْرِهَ": { rank: 10099, meaning: "to compel" },
  "عَقَرَ": { rank: 7077, meaning: "to hamstrung" },
  "سَلَفَ": { rank: 2275, meaning: "to pass" },
  "أَوْقَدُ": { rank: 5064, meaning: "to kindle" },
  "سُيِّرَتْ": { rank: 10022, meaning: "to travel" },
  "أَوْصَٰ": { rank: 4011, meaning: "to instruct" },
  "شَرَحَ": { rank: 6125, meaning: "to expand" },
  "ٱسْتَبَقَ": { rank: 2148, meaning: "to race" },
  "نَصَحُ": { rank: 7062, meaning: "to advise" },
  "أَوَى": { rank: 11043, meaning: "to betake" },
  "ٱسْتَخْلَفَ": { rank: 6133, meaning: "to grant succession" },
  "أَلَّفَ": { rank: 3103, meaning: "to make friendship" },
  "طَعِمُ": { rank: 2249, meaning: "to taste" },
  "طُمِسَتْ": { rank: 4047, meaning: "to efface" },
  "عَتَ": { rank: 7077, meaning: "to grant" },
  "عَجِلَ": { rank: 7150, meaning: "to be patient" },
  "عَجَّلَ": { rank: 10011, meaning: "to hasten" },
  "يَبْخَسْ": { rank: 2282, meaning: "to diminish" },
  "ٱهْجُرْ": { rank: 4034, meaning: "to forsake" },
  "يَمْتَرُ": { rank: 6002, meaning: "to doubt" },
  "يَرْهَقُ": { rank: 10026, meaning: "to cover" },
  "تَقَرَّ": { rank: 19026, meaning: "to cool" },
  "يَعْتَذِرُ": { rank: 9066, meaning: "to make excuse" },
  "تَوَاصَ": { rank: 51053, meaning: "to transmit" },
  "تَطَهَّرْ": { rank: 2222, meaning: "to purify" },
  "يَجْهَلُ": { rank: 6111, meaning: "to be ignorant" },
  "تَّقَطَّعَ": { rank: 2166, meaning: "to cut off" },
  "يُؤَدِّ": { rank: 2283, meaning: "to discharge" },
  "تَعْثَ": { rank: 2060, meaning: "to be wicked" },
  "يَعْرُجُ": { rank: 15014, meaning: "to ascend" },
  "جَهَرَ": { rank: 13010, meaning: "to publicize" },
  "يَشْفَعُ": { rank: 2255, meaning: "to intercede" },
  "يَرْكَعُ": { rank: 2043, meaning: "to bow down" },
  "أَصَرُّ": { rank: 3135, meaning: "to persist" },
  "تَمَّ": { rank: 6115, meaning: "to fulfill" },
  "ٱخْتَارَ": { rank: 7155, meaning: "to chose" },
  "نَّزَغَ": { rank: 7200, meaning: "to whisper evil suggestions" },
  "أُهِلَّ": { rank: 2173, meaning: "to dedicate" },
  "يُبْطِلَ": { rank: 2264, meaning: "to render in vain" },
  "تَأْسَ": { rank: 5026, meaning: "to grieve" },
  "مَكَثَ": { rank: 13017, meaning: "to remain" },
  "هَاتُ": { rank: 2111, meaning: "to bring" },
  "يَسْتَعْتِبُ": { rank: 16084, meaning: "to make amends" },
  "عَمَرُ": { rank: 9017, meaning: "to maintain" },
  "ثَقُلَتْ": { rank: 7008, meaning: "to be heavy" },
  "مَضَىٰ": { rank: 8038, meaning: "to precede" },
  "يَسْتَقْدِمُ": { rank: 7034, meaning: "to seek to advance" },
  "تَنَٰجَيْ": { rank: 58008, meaning: "to hold secret meetings" },
  "سَرَقَ": { rank: 12077, meaning: "to steal" },
  "يَتَكَلَّمُ": { rank: 11105, meaning: "to speak" },
  "جَاوَزَ": { rank: 2249, meaning: "to cross" },
  "لَمَسُ": { rank: 4043, meaning: "to touch" },
  "بَيَّتَ": { rank: 4081, meaning: "o spend the night" },
  "تَشَٰبَهَ": { rank: 2070, meaning: "to look alike" },
  "عَزَمَ": { rank: 2227, meaning: "to resolve" },
  "أَقْرَرْ": { rank: 2084, meaning: "to ratify" },
  "رَبَتْ": { rank: 22005, meaning: "to swell" },
  "صَوَّرَ": { rank: 3006, meaning: "to shape" },
  "أَنۢبَأَ": { rank: 2031, meaning: "to inform" },
  "صَبَّ": { rank: 22019, meaning: "to pour" },
  "ٱسْتَخْرَجَ": { rank: 12076, meaning: "to bring out" },
  "ٱسْتَحَبُّ": { rank: 9023, meaning: "to prefer" },
  "شَقُ": { rank: 11106, meaning: "to wretched" },
  "نَذَرْ": { rank: 2270, meaning: "to vow" },
  "أَلْهَىٰ": { rank: 15003, meaning: "to divert" },
  "يَرْغَبُ": { rank: 2130, meaning: "to turn away" },
  "ٱرْتَقِبْ": { rank: 11093, meaning: "to watch" },
  "يَنْحِتُ": { rank: 7074, meaning: "to carve out" },
  "شَرَ": { rank: 2102, meaning: "to sold" },
  "يَدْرَؤُا۟": { rank: 3168, meaning: "to avert" },
  "أَلْحَقْ": { rank: 12101, meaning: "to join" },
  "أُغْشِيَتْ": { rank: 7054, meaning: "to cover" },
  "نَفِدَ": { rank: 16096, meaning: "to be exhausted" },
  "يَسُومُ": { rank: 2049, meaning: "to afflict" },
  "يَخْرُصُ": { rank: 6116, meaning: "to guess" },
  "ٱسْتَعِذْ": { rank: 7200, meaning: "to seek refuge" },
  "نَقَمُ": { rank: 5059, meaning: "to resent" },
  "ٱسْتَعِينُ": { rank: 1005, meaning: "to ask for help" },
  "ٱسْتَغَٰثَ": { rank: 8009, meaning: "to seek help" },
  "أَكْرَمَ": { rank: 12021, meaning: "to make comfortable" },
  "سَوَّلَ": { rank: 12018, meaning: "to entice" },
  "أُزْلِفَتْ": { rank: 26064, meaning: "to bring" },
  "ٱسْتَغْنَىٰ": { rank: 64006, meaning: "to manage without" },
  "أُصْلِي": { rank: 4030, meaning: "to cast" },
  "وَسْوَسَ": { rank: 7020, meaning: "to whisper" },
  "صَدَفَ": { rank: 6046, meaning: "to turn away" },
  "أَنقَذَ": { rank: 3103, meaning: "to save" },
  "تَلَقَّىٰٓ": { rank: 2037, meaning: "to receive" },
  "حُلُّ": { rank: 18031, meaning: "to be adorned" },
  "يَغُضُّ": { rank: 24030, meaning: "to lower" },
  "يُدَبِّرُ": { rank: 10003, meaning: "to dispose" },
  "يُصَلَّبُ": { rank: 5033, meaning: "to be crucified" },
  "يُحَرِّفُ": { rank: 2075, meaning: "to distort" },
  "ٱقْتَتَلَ": { rank: 2253, meaning: "to fight each other" },
  "أَجْمَعُ": { rank: 10071, meaning: "to resolve" },
  "يَتَدَبَّرُ": { rank: 4082, meaning: "to ponder" },
  "يُحَافِظُ": { rank: 2238, meaning: "to guard strictly" },
  "وَٰعَدْ": { rank: 2051, meaning: "to appoint" },
  "ٱقْتَرَفْ": { rank: 6113, meaning: "to commit" },
  "أَحْبَطَ": { rank: 33019, meaning: "to make worthless" },
  "خَرَقَ": { rank: 6100, meaning: "to make falsely attribute" },
  "فَشِلْ": { rank: 3122, meaning: "to lose heart" },
  "وُۥرِىَ": { rank: 5031, meaning: "to hide" },
  "أَدْبَرَ": { rank: 70017, meaning: "to turn back" },
  "حَيَّ": { rank: 4086, meaning: "to greet" },
  "خَابَ": { rank: 14015, meaning: "to disappoint" },
  "يُعْجِزَ": { rank: 8059, meaning: "to escape" },
  "يُغَيِّرُ": { rank: 4119, meaning: "to change" },
  "يُحِقَّ": { rank: 8007, meaning: "to justify" },
  "تَمَارَ": { rank: 42018, meaning: "to dispute" },
  "يَتَبَوَّأُ": { rank: 10087, meaning: "to settle" },
  "كَبِّرْ": { rank: 2185, meaning: "to magnify" },
  "ٱهْتَزَّتْ": { rank: 22005, meaning: "to stirr" },
  "قُدَّ": { rank: 12025, meaning: "to tear" },
  "قُتِّلُ": { rank: 5033, meaning: "to kill" },
  "قَفَّيْ": { rank: 2087, meaning: "to follow up" },
  "قَنَطُ": { rank: 15056, meaning: "to despair" },
  "يُخَوِّفُ": { rank: 3175, meaning: "to frighten" },
  "ٱنفَضُّ": { rank: 3159, meaning: "to disperse" },
  "أَنشَرَ": { rank: 21021, meaning: "to raise" },
  "يَلِجَ": { rank: 7040, meaning: "to pass" },
  "تَيَمَّمُ": { rank: 2267, meaning: "to aim" },
  "أَحْضَرَتْ": { rank: 4128, meaning: "to sway" },
  "ٱسْتَفْتَحُ": { rank: 2089, meaning: "to pray for victory" },
  "يَلْ": { rank: 3078, meaning: "to distort" },
  "أَلْفَ": { rank: 2170, meaning: "to find" },
  "يَغِيظُ": { rank: 9120, meaning: "to be angry" },
  "طَفِقَ": { rank: 7022, meaning: "to begin" },
  "تُرْجِى": { rank: 7111, meaning: "to postpone" },
  "تُحَدِّثُ": { rank: 2076, meaning: "to tell" },
  "أَلْزَمَ": { rank: 11028, meaning: "to compel" },
  "قَسَتْ": { rank: 2074, meaning: "to harden" },
  "طَرَد": { rank: 6052, meaning: "to send away" },
  "أَحَسَّ": { rank: 3052, meaning: "to perceive" },
  "أَثَٰبَ": { rank: 3153, meaning: "to repay" },
  "طَالَ": { rank: 20086, meaning: "to last long" },
  "يَرْهَبُ": { rank: 2040, meaning: "to fear" },
  "أَبْرَحَ": { rank: 12080, meaning: "to leave" },
  "ٱمْسَحُ": { rank: 4043, meaning: "to wipe" },
  "طَابَ": { rank: 4003, meaning: "to be suitable" },
  "أَكْنَن": { rank: 2235, meaning: "to conceal" },
  "يَعْصِمُ": { rank: 5067, meaning: "to protect" },
  "يَسْتَبْدِلْ": { rank: 2061, meaning: "to exchange" },
  "ٱعْتَرَفُ": { rank: 9102, meaning: "to acknowledge" },
  "كَسَوْ": { rank: 2259, meaning: "to cover them" },
  "أَضَآءَ": { rank: 2017, meaning: "to illuminate" },
  "فَاتَ": { rank: 3153, meaning: "to escape" },
  "لُمْ": { rank: 12032, meaning: "to blame" },
  "يَسَْٔمُ": { rank: 2282, meaning: "to be weary" },
  "يَشَّقَّقُ": { rank: 2074, meaning: "to split" },
  "ٱسْتَخَفَّ": { rank: 16080, meaning: "to underestimate" },
  "تَنفُذُ": { rank: 55033, meaning: "to pass beyond" },
  "كُبِتَ": { rank: 3127, meaning: "to suppress" },
  "عَنِ": { rank: 3118, meaning: "to distresses" },
  "تَنتَشِرُ": { rank: 30020, meaning: "to disperse" },
  "غَوَىٰ": { rank: 20121, meaning: "to err" },
  "كُوِّرَتْ": { rank: 39005, meaning: "to wrap" },
  "ٱصْطَبِرْ": { rank: 19065, meaning: "to be constant" },
  "أَسَّسَ": { rank: 9108, meaning: "to find" },
  "ٱطَّيَّرْ": { rank: 7131, meaning: "to ascribe evil omens" },
  "تَمِيدَ": { rank: 16015, meaning: "to shake" },
  "تَلْقَفُ": { rank: 7117, meaning: "to swallow" },
  "غَدَ": { rank: 3121, meaning: "to leave early morning" },
  "تَمَنَّىٰٓ": { rank: 22052, meaning: "to recite" },
  "غَشَّىٰ": { rank: 8011, meaning: "to cover" },
  "فَارَ": { rank: 11040, meaning: "to overflow" },
  "أَطْفَأَ": { rank: 5064, meaning: "to extinguish" },
  "أَفْرِغْ": { rank: 2250, meaning: "to pour" },
  "كَنَزْ": { rank: 9034, meaning: "to hoard" },
  "يَعْدُ": { rank: 4154, meaning: "to transgress" },
  "أَفَلَ": { rank: 6076, meaning: "to set" },
  "يَمِيلُ": { rank: 4027, meaning: "to deviate" },
  "ٱسْتَكْثَرْ": { rank: 6128, meaning: "to mislead" },
  "أَذَّنَ": { rank: 7044, meaning: "to announce" },
  "يَسْتَخْفُ": { rank: 4108, meaning: "to seek to hide" },
  "فَسَدَتِ": { rank: 2251, meaning: "to corrupt" },
  "فَزِعَ": { rank: 27087, meaning: "to be terrified" },
  "أَرْدَىٰ": { rank: 6137, meaning: "tio ruin" },
  "يَطَؤ": { rank: 9120, meaning: "to step" },
  "ٱسْتَمْسَكَ": { rank: 2256, meaning: "to grasp" },
  "يَسْتَعْفِفْ": { rank: 4006, meaning: "to refrain" },
  "يَسْتَفِزَّ": { rank: 17064, meaning: "to incite" },
  "ٱسْتَنكَفُ": { rank: 4172, meaning: "to disdain" },
  "يَلْمِزُ": { rank: 9058, meaning: "to criticize" },
  "فَآءُ": { rank: 2226, meaning: "to return" },
  "مَحَوْ": { rank: 13039, meaning: "to eliminate" },
  "عَزَّرُ": { rank: 5012, meaning: "to assist" },
  "فَازَ": { rank: 3185, meaning: "to succeed" },
  "أَفَآءَ": { rank: 33050, meaning: "to give" },
  "حَسَدَ": { rank: 4054, meaning: "to be jealous" },
  "حَسُنَ": { rank: 4069, meaning: "to be excellent" },
  "ٱحْتَمَلَ": { rank: 4112, meaning: "to burdeb oneself" },
  "خَوَّلَ": { rank: 6094, meaning: "to bestow" },
  "يُرْضُ": { rank: 9008, meaning: "to satisfy" },
  "زُلْزِلُ": { rank: 2214, meaning: "to be shaken" },
  "يُنكِرُ": { rank: 13036, meaning: "to deny" },
  "يَجْرِمَ": { rank: 5002, meaning: "to incite" },
  "يَجَْٔرُ": { rank: 16053, meaning: "to cry for help" },
  "يُذَبِّحُ": { rank: 2049, meaning: "to slaughter" },
  "خَاطَبَ": { rank: 11037, meaning: "to address" },
  "حَالَ": { rank: 8024, meaning: "to come" },
  "سَحَرُ": { rank: 7116, meaning: "to bewitch" },
  "يَأْلَمُ": { rank: 4104, meaning: "to suffer" },
  "تُنكِحُ": { rank: 2221, meaning: "to give in marriage" },
  "سَرِّحُ": { rank: 2231, meaning: "to release" },
  "يَحْتَسِبُ": { rank: 39047, meaning: "to take into account" },
  "وُقِفُ": { rank: 6027, meaning: "to be made to stand" },
  "بَصُرَتْ": { rank: 20096, meaning: "to perceive" },
  "يَكْفُلُ": { rank: 3044, meaning: "to take charge of" },
  "وَّزَنُ": { rank: 17035, meaning: "to weigh" },
  "يُرْهِقَ": { rank: 18073, meaning: "to be hard upon" },
  "خَطِفَ": { rank: 2020, meaning: "to snatch away" },
  "تَأَخَّرَ": { rank: 2203, meaning: "to delay" },
  "خَفَّتْ": { rank: 7009, meaning: "to be light" },
  "زَهَقَ": { rank: 9055, meaning: "to depart" },
  "بَقِىَ": { rank: 2278, meaning: "to remain" },
  "وَجِلَتْ": { rank: 8002, meaning: "to fear" },
  "يُسْجَنَ": { rank: 12025, meaning: "to imprison" },
  "زَالَ": { rank: 14046, meaning: "to move" },
  "يُوزَعُ": { rank: 27017, meaning: "to set in rows" },
  "يُبْدِلَ": { rank: 18081, meaning: "to change" },
  "يُبْدِئُ": { rank: 29019, meaning: "to originate" },
  "ٱبْيَضَّتْ": { rank: 3106, meaning: "to become white" },
  "يَتَعَدَّ": { rank: 2229, meaning: "to transgress" },
  "ٱخْتَلَطَ": { rank: 6146, meaning: "to join" },
  "يُمْنَىٰ": { rank: 53046, meaning: "to emit" },
  "سُقِطَ": { rank: 6059, meaning: "to fall" },
  "يَرْكُضُ": { rank: 21012, meaning: "to flee" },
  "حَرِّقُ": { rank: 20097, meaning: "to burn" },
  "أَوْجَسَ": { rank: 11070, meaning: "to feel apprehension" },
  "يَتَبَدَّلِ": { rank: 2108, meaning: "to exchange" },
  "يَتَخَطَّفَ": { rank: 8026, meaning: "to do away with you" },
  "يَتَضَرَّعُ": { rank: 6042, meaning: "to be humble" },
  "يَرْقُبُ": { rank: 9008, meaning: "to watch over" },
  "حَرَصْ": { rank: 4129, meaning: "to desire" },
  "تُسْقِطَ": { rank: 17092, meaning: "to cause to fall" },
  "يَدَّعُ": { rank: 36057, meaning: "to call for" },
  "ٱرْتَضَىٰ": { rank: 21028, meaning: "to approve" },
  "يُحْدِثُ": { rank: 18070, meaning: "to present" },
  "يُلَٰقُ": { rank: 43083, meaning: "to meet" },
  "يُلْحِدُ": { rank: 7180, meaning: "to deviate" },
  "رَّبَطْ": { rank: 8011, meaning: "to strengthen" },
  "ٱخْفِضْ": { rank: 15088, meaning: "to lower" },
  "رَاغَ": { rank: 37091, meaning: "to turn" },
  "أُتْرِفُ": { rank: 11116, meaning: "to give luxury" },
  "نََٔا": { rank: 6026, meaning: "to keep away" },
  "نُشِرَتْ": { rank: 18016, meaning: "to spread" },
  "تُقْسِطُ": { rank: 4003, meaning: "to do justice" },
  "ٱدَّٰرَكَ": { rank: 7038, meaning: "to overtake" },
  "حَاسَبْ": { rank: 2284, meaning: "to account" },
  "نُسِفَتْ": { rank: 20097, meaning: "to scatter" },
  "يُمِلَّ": { rank: 2282, meaning: "to dictate" },
  "يُضَآرَّ": { rank: 2233, meaning: "to suffer" },
  "يَتَرَقَّبُ": { rank: 28018, meaning: "to be vigilant" },
  "يُحَذِّرُ": { rank: 3028, meaning: "to warn" },
  "يُسْحَبُ": { rank: 40071, meaning: "to drag" },
  "يُشْعِرُ": { rank: 6109, meaning: "to perceive" },
  "يَلْتَفِتْ": { rank: 11081, meaning: "to look back" },
  "يُحَآدُّ": { rank: 58005, meaning: "to oppose" },
  "ٱغْلُظْ": { rank: 9073, meaning: "to be stern" },
  "يَطَّوَّفَ": { rank: 2158, meaning: "to walk" },
  "يُطَاعُ": { rank: 4064, meaning: "to obey" },
  "يَمِيزَ": { rank: 3179, meaning: "to separate" },
  "يَلْحَقُ": { rank: 3170, meaning: "to joined" },
  "يَلْهَثْ": { rank: 7176, meaning: "to pant" },
  "يُرَآءُ": { rank: 4142, meaning: "to show off" },
  "وُكِّلَ": { rank: 6089, meaning: "to entrust" },
  "يَتَخَٰفَتُ": { rank: 20103, meaning: "to murmur" },
  "يُحَكِّمُ": { rank: 4065, meaning: "to judge" },
  "يَبُورُ": { rank: 35010, meaning: "to perish" },
  "يُحْبَرُ": { rank: 30015, meaning: "to be delighted" },
  "يُخَالِفُ": { rank: 11088, meaning: "to differ from" },
  "يَفْسَحِ": { rank: 58011, meaning: "to make room" },
  "كَثُرَ": { rank: 4007, meaning: "to multiply" },
  "يُخَٰدِعُ": { rank: 2009, meaning: "to deceive" },
  "ٱنشُزُ": { rank: 58011, meaning: "to rise up" },
  "يَفْجُرَ": { rank: 17090, meaning: "to gush forth" },
  "يَتَخَيَّرُ": { rank: 56020, meaning: "to select" },
  "يُخْسِرُ": { rank: 55009, meaning: "to make deficient" },
  "ٱنسَلَخَ": { rank: 7175, meaning: "to be detached" },
  "يُدْحِضُ": { rank: 18056, meaning: "to refute" },
  "يَطْمِثْ": { rank: 55056, meaning: "to touch" },
  "يَعْصِرُ": { rank: 12036, meaning: "to press" },
  "يَعْزُبُ": { rank: 10061, meaning: "to escape" },
  "يَأْتَمِرُ": { rank: 28020, meaning: "to counsel" },
  "يُدْهِنُ": { rank: 68009, meaning: "to compromise" },
  "ٱنتَبَذَتْ": { rank: 19016, meaning: "to withdraw" },
  "يَعْرِشُ": { rank: 7137, meaning: "to erect" },
  "يُعَظِّمْ": { rank: 22030, meaning: "to honor" },
  "كَرَّمْ": { rank: 17062, meaning: "to honor" },
  "ٱمْتَحَنَ": { rank: 49003, meaning: "to test" },
  "ٱلْتَقَطَ": { rank: 12010, meaning: "to pick" },
  "يُزْجِى": { rank: 17066, meaning: "to drive" },
  "ٱكْتَالُ": { rank: 12063, meaning: "to measure" },
  "يُحَاوِرُ": { rank: 18034, meaning: "to talk" },
  "يُهَيِّئْ": { rank: 18010, meaning: "to facilitate" },
  "يُعَقِّبْ": { rank: 27010, meaning: "to look back" },
  "يَتَمَآسَّ": { rank: 58003, meaning: "to touch" },
  "يَحُضُّ": { rank: 69034, meaning: "to feel the urge" },
  "يَمْحَقُ": { rank: 2276, meaning: "to destroy" },
  "يَنسَخُ": { rank: 2106, meaning: "to abrogate" },
  "يَحْبِسُ": { rank: 5106, meaning: "to detain" },
  "يَنسِلُ": { rank: 21096, meaning: "to descend" },
  "ٱسْتَكَانُ": { rank: 3146, meaning: "to give in" },
  "نُصِبَتْ": { rank: 88019, meaning: "to fix" },
  "يَسْبَحُ": { rank: 21033, meaning: "to float" },
  "مَهِّلِ": { rank: 73011, meaning: "to allow for respite" },
  "يَهِيجُ": { rank: 39021, meaning: "to wither" },
  "مُزِّقْ": { rank: 34007, meaning: "to disintegrate" },
  "ٱسْتَغْشَ": { rank: 11005, meaning: "to cover oneself" },
  "يَخْتَانُ": { rank: 2187, meaning: "to deceive" },
  "نَكَصَ": { rank: 8048, meaning: "to turn away" },
  "يَخْتَصُّ": { rank: 2105, meaning: "to choose" },
  "يَخْدَعُ": { rank: 2009, meaning: "to deceive" },
  "يَخْصِفَ": { rank: 7022, meaning: "to fasten" },
  "يَسُبُّ": { rank: 6108, meaning: "to insult" },
  "يَزْنُ": { rank: 25068, meaning: "to commit unlawful sex" },
  "يَخْلُدْ": { rank: 25069, meaning: "to abide forever" },
  "يَدُعُّ": { rank: 52013, meaning: "to thrust" },
  "نَافَقُ": { rank: 3167, meaning: "to be hypocrite" },
  "ٱسْتَشْهِدُ": { rank: 2282, meaning: "to call for evidence" },
  "ٱسْتَسْقَىٰ": { rank: 2060, meaning: "to ask water" },
  "نَجَا": { rank: 12045, meaning: "to save" },
  "نَسْتَدْرِجُ": { rank: 7182, meaning: "to gradually lead them" },
  "ٱسْتَحَقَّ": { rank: 5107, meaning: "to be guilty" },
  "ٱجْلِدُ": { rank: 24002, meaning: "to flog" },
  "ٱجْتَمَعُ": { rank: 17088, meaning: "to gather" },
  "يُغَادِرُ": { rank: 18047, meaning: "to leave behind" },
  "ٱسْتَنصَرَ": { rank: 8072, meaning: "to seek help" },
  "يَتَعَارَفُ": { rank: 10045, meaning: "to recognize" },
  "يُثْبِتُ": { rank: 8030, meaning: "to restrain" },
  "يُمَحِّصَ": { rank: 3141, meaning: "to purify" },
  "يُمَنِّي": { rank: 4119, meaning: "to arise desires" },
  "يَصُمْ": { rank: 2184, meaning: "to fast" },
  "يَشْفِ": { rank: 9014, meaning: "to heal" },
  "يُبْلِىَ": { rank: 3186, meaning: "to be tested" },
  "ٱضْمُمْ": { rank: 20022, meaning: "to draw near" },
  "يَتَعَلَّمُ": { rank: 2102, meaning: "to learn" },
  "يُنزَفُ": { rank: 37047, meaning: "to be intoxicated" },
  "وَرَدَ": { rank: 21099, meaning: "to come to" },
  "ٱسْتَحْوَذَ": { rank: 4141, meaning: "to have advantage" },
  "يُهْرَعُ": { rank: 11078, meaning: "to rush" },
  "وَجَّهْ": { rank: 6079, meaning: "to have turned" },
  "لُمَّ": { rank: 6150, meaning: "to bring forward" },
  "ٱشْتَمَلَتْ": { rank: 6143, meaning: "to contain" },
  "لِن": { rank: 3159, meaning: "to deal gently" },
  "ٱسْوَدَّتْ": { rank: 3106, meaning: "to become black" },
  "لَّجُّ": { rank: 23075, meaning: "to persist" },
  "ٱسْتَْٔجَرْ": { rank: 28026, meaning: "to hire" },
  "يَتَكَبَّرُ": { rank: 7013, meaning: "to be arrogant" },
  "يَسْفِكُ": { rank: 2030, meaning: "to shed" },
  "مَرَجَ": { rank: 25053, meaning: "to release" },
  "ٱسْتَئَْسَ": { rank: 12080, meaning: "to despair" },
  "ٱسْتَيْقَنَتْ": { rank: 27014, meaning: "to convince" },
  "ٱسْتَيْسَرَ": { rank: 2196, meaning: "to obtained with ease" },
  "هَزَمُ": { rank: 2251, meaning: "to defeat" },
  "يَقْنُتْ": { rank: 3043, meaning: "to be obedient" },
  "ءَاذَن": { rank: 21109, meaning: "to announce" },
  "كَالُ": { rank: 17035, meaning: "to measure" },
  "تَرَآءَتِ": { rank: 8048, meaning: "to come in sight" },
  "تَيَسَّرَ": { rank: 73020, meaning: "to ease" },
  "تَوَارَتْ": { rank: 16059, meaning: "to hide" },
  "تَنْهَرْ": { rank: 17023, meaning: "to repeal" },
  "تَمُورُ": { rank: 52009, meaning: "to shake" },
  "تَقَوَّلَ": { rank: 52033, meaning: "to make up" },
  "تَقَدَّمَ": { rank: 48002, meaning: "to precede" },
  "تَفْقِدُ": { rank: 12071, meaning: "to miss" },
  "تَفِيضُ": { rank: 5083, meaning: "to overflow" },
  "تَغْلُو": { rank: 4171, meaning: "to commit excess" },
  "تَعْضُلُ": { rank: 2232, meaning: "to hinder" },
  "تَعَاوَنُ": { rank: 5002, meaning: "to help one another" },
  "تَظَٰهَرُ": { rank: 2085, meaning: "to support one another" },
  "تَطَوَّعَ": { rank: 2158, meaning: "to volunteer" },
  "تَصْطَلُ": { rank: 27007, meaning: "to warm yourselves" },
  "تَزْرَعُ": { rank: 12047, meaning: "tol sow" },
  "تَرْكَنُ": { rank: 11113, meaning: "to incline" },
  "تَرْجُفُ": { rank: 73014, meaning: "to quake" },
  "تُبْرِئُ": { rank: 3049, meaning: "to cure" },
  "تُصَٰحِبْ": { rank: 18076, meaning: "to keep as companion" },
  "جَلَّىٰ": { rank: 7187, meaning: "to reveal" },
  "ذُلِّلَتْ": { rank: 36072, meaning: "to tame" },
  "سَخِطَ": { rank: 5080, meaning: "to become angry" },
  "زَلَلْ": { rank: 2209, meaning: "to slip" },
  "رَٰعِ": { rank: 2104, meaning: "to consider" },
  "رَعَ": { rank: 20054, meaning: "to pasture" },
  "رَحُبَتْ": { rank: 9025, meaning: "to be spacious" },
  "رَتَّلْ": { rank: 25032, meaning: "to recite" },
  "رَبَّيَ": { rank: 17024, meaning: "to bring up" },
  "دُكَّتِ": { rank: 69014, meaning: "to crush" },
  "جَنَحُ": { rank: 8061, meaning: "to incline" },
  "دَنَا": { rank: 33059, meaning: "to draw" },
  "خَشَعَتِ": { rank: 20108, meaning: "to be humbled" },
  "حَصِرَتْ": { rank: 4090, meaning: "to restrain" },
  "حَرِّضِ": { rank: 4084, meaning: "to encourage" },
  "حَآدَّ": { rank: 9063, meaning: "to oppose" },
  "حَارَبَ": { rank: 5033, meaning: "to wage war" },
  "جَهَّزَ": { rank: 12059, meaning: "to furnish" },
  "تَرَٰضَ": { rank: 2232, meaning: "to agree" },
  "تَجَلَّىٰ": { rank: 7143, meaning: "to reveal glory" },
  "شَرَعَ": { rank: 42013, meaning: "to ordain" },
  "تَبْتَئِسْ": { rank: 11036, meaning: "to distress" },
  "أَكْثَرُ": { rank: 11032, meaning: "to be frequent" },
  "أَغْرَيْ": { rank: 5014, meaning: "to tempt" },
  "أَعَانَ": { rank: 18095, meaning: "to assist" },
  "أَصْفَىٰ": { rank: 17040, meaning: "to choose" },
  "أَشْفَقْ": { rank: 33072, meaning: "to fear" },
  "أَسْلَفَتْ": { rank: 10030, meaning: "to lend" },
  "أَزَاغَ": { rank: 3008, meaning: "to deviate" },
  "أَرْكَسَ": { rank: 4088, meaning: "to cast them back" },
  "أَرْبَىٰ": { rank: 2276, meaning: "to increase" },
  "أَدْلَىٰ": { rank: 2188, meaning: "to present" },
  "أَخْلَصُ": { rank: 4146, meaning: "to be sincere" },
  "أَخْلَدَ": { rank: 7176, meaning: "to adhere" },
  "أَخْطَأْ": { rank: 2286, meaning: "to err" },
  "أَخْبَتُ": { rank: 11023, meaning: "to be humble" },
  "أَجَّلَ": { rank: 6128, meaning: "to appoint" },
  "أَثْمَرَ": { rank: 6099, meaning: "to bear fruit" },
  "أَثْخَن": { rank: 8067, meaning: "to battle strenuously" },
  "أَكْمَلْ": { rank: 2185, meaning: "to complete" },
  "أَنصِتُ": { rank: 7204, meaning: "to pay attention" },
  "أَنطَقَ": { rank: 41021, meaning: "to make to speak" },
  "بَٰشِرُ": { rank: 2187, meaning: "to have relations" },
  "تَبَّرْ": { rank: 17007, meaning: "to destroy" },
  "تَبَّ": { rank: 111001, meaning: "to perish" },
  "تَبَرُّ": { rank: 2224, meaning: "to do good" },
  "تَأَذَّنَ": { rank: 7167, meaning: "to declare" },
  "بُهِتَ": { rank: 2258, meaning: "to became dumbfounded" },
  "بُعْثِرَ": { rank: 82004, meaning: "to be overturned" },
  "بُرِّزَتِ": { rank: 26091, meaning: "to manifest" },
  "بَعُدَتْ": { rank: 9042, meaning: "to long" },
  "أَهَٰنَ": { rank: 22018, meaning: "to humiliate" },
  "بَطَنَ": { rank: 6151, meaning: "to conceal" },
  "بَرَّأَ": { rank: 12053, meaning: "to absolve" },
  "أُحْكِمَتْ": { rank: 11001, meaning: "to perfect" },
  "أُحْصِرُ": { rank: 2196, meaning: "to hold back" },
  "أُبْسِلُ": { rank: 6070, meaning: "to give up to destruction" },
  "أَوْعَىٰٓ": { rank: 70018, meaning: "to hoard" },
  "أَوْزِعْ": { rank: 27019, meaning: "to grant power" },
  "سَلَّطَ": { rank: 4090, meaning: "to give power" },
  "عَضُّ": { rank: 3119, meaning: "to bite" },
  "صَمُّ": { rank: 5071, meaning: "to become deaf" },
  "غَنِمْ": { rank: 8041, meaning: "to obtain" },
  "ظَلَّلْ": { rank: 2057, meaning: "to shade" },
  "عَرَّفَ": { rank: 47006, meaning: "to make it known" },
  "ضَعُفَ": { rank: 3146, meaning: "to weaken" },
  "طَلَعَت": { rank: 18017, meaning: "to rise" },
  "شَقَقْ": { rank: 28027, meaning: "to make it difficult" },
  "قَدِمْ": { rank: 11098, meaning: "to precede" },
  "غِيضَ": { rank: 11044, meaning: "to subside" },
  "قَسَمْ": { rank: 43032, meaning: "to distribute" },
  "عَبَسَ": { rank: 74022, meaning: "to frown" },
  "صَلَحَ": { rank: 13023, meaning: "to be righteous" },
  "قَيَّضْ": { rank: 41025, meaning: "to be destined" },
  "عَيِي": { rank: 46033, meaning: "to be tired" },
  "صَلَبُ": { rank: 4157, meaning: "to be crucified" },
  "صَغَتْ": { rank: 6113, meaning: "to incline" },
  "غَرَبَت": { rank: 18017, meaning: "to set" },
  "فَرَغْ": { rank: 55031, meaning: "to attend" },
  "صَعِقَ": { rank: 39068, meaning: "to faint" },
  "يُغَاثُ": { rank: 18029, meaning: "to relieve" },
  "يُطَوَّقُ": { rank: 3180, meaning: "to surround" },
  "يُطِيقُ": { rank: 2184, meaning: "to afford" },
  "يُطْلِعَ": { rank: 3179, meaning: "to inform" },
  "تَبَتَّلْ": { rank: 73008, meaning: "to devote oneself" },
  "تَبَرَّجْ": { rank: 33033, meaning: "to display" },
  "عَقَدَتْ": { rank: 4033, meaning: "to pledge" },
  "تَبَسَّمَ": { rank: 27019, meaning: "to smiled" },
  "تَحَسَّسُ": { rank: 12087, meaning: "to inquire" },
  "يُمَسِّكُ": { rank: 7170, meaning: "to hold fast" },
  "تَحَرَّ": { rank: 72014, meaning: "to seek" },
  "تَبِيدَ": { rank: 18035, meaning: "to perish" },
  "ءَاسَفُ": { rank: 43055, meaning: "to anger" },
  "عَسْعَسَ": { rank: 81017, meaning: "to depart" },
  "تَجُوعَ": { rank: 20118, meaning: "to be hungry" },
  "عَزَّزْ": { rank: 36014, meaning: "to strengthen" },
  "يُقْصِرُ": { rank: 7202, meaning: "to cease" },
  "يُقَلِّلُ": { rank: 8044, meaning: "to lessen" },
  "عَزَّ": { rank: 38023, meaning: "to overpowere" },
  "يُفَتَّرُ": { rank: 43075, meaning: "to be subside" },
  "تَتَقَلَّبُ": { rank: 24037, meaning: "to turn about" },
  "تَجَسَّسُ": { rank: 49012, meaning: "to spy" },
  "يُغَاثُ2": { rank: 12049, meaning: "to send abundant rain" },
  "يُعْظِمْ": { rank: 65005, meaning: "to magnify" },
  "تَتَجَافَىٰ": { rank: 32016, meaning: "to forsake" },
  "شَغَفَ": { rank: 12030, meaning: "to be filled with passion" },
  "تَبَايَعْ": { rank: 2282, meaning: "to trade" },
  "بَطِرَتْ": { rank: 28058, meaning: "to be arrogant" },
  "ٱؤْتُمِنَ": { rank: 2283, meaning: "to entrust" },
  "ٱبْتَدَعُ": { rank: 57027, meaning: "to innovate" },
  "بَٰعِدْ": { rank: 34019, meaning: "to lengthen" },
  "ٱبْلَعِ": { rank: 11044, meaning: "to swallow" },
  "عُثِرَ": { rank: 5107, meaning: "to discover" },
  "عُطِّلَتْ": { rank: 81004, meaning: "to leave untended" },
  "ٱتَّسَقَ": { rank: 84018, meaning: "to become full" },
  "يُنفَ": { rank: 5033, meaning: "to be excile" },
  "عُمِّيَتْ": { rank: 11028, meaning: "to become blind" },
  "ٱثَّاقَلْ": { rank: 9038, meaning: "to cling heavily" },
  "ٱثْبُتُ": { rank: 8045, meaning: "to be firm" },
  "بَطَلَ": { rank: 7118, meaning: "to become futile" },
  "ٱجْتَرَحُ": { rank: 45021, meaning: "to commit" },
  "بَسَرَ": { rank: 74022, meaning: "to scowl" },
  "يُوَفِّقِ": { rank: 4035, meaning: "to reconcile" },
  "يُوَاطِؤ": { rank: 9037, meaning: "to adjust" },
  "بُسَّتِ": { rank: 56005, meaning: "to be crumbled" },
  "عَنَتِ": { rank: 20111, meaning: "to be humbled" },
  "يُوقِعَ": { rank: 5091, meaning: "to cause" },
  "يُوفِضُ": { rank: 70043, meaning: "to haste" },
  "يُوصِي": { rank: 4012, meaning: "to make" },
  "لَوَّ": { rank: 63005, meaning: "to turn aside" },
  "يُوثِقُ": { rank: 89026, meaning: "to bind" },
  "يُوبِقْ": { rank: 42034, meaning: "to destroy" },
  "عَقَّد": { rank: 5089, meaning: "to contract" },
  "تَأْجُرَ": { rank: 28027, meaning: "to serve" },
  "يُنْغِضُ": { rank: 17051, meaning: "to shake" },
  "يُنَٰزِعُ": { rank: 22067, meaning: "to struggle with" },
  "يُنَشَّؤُا۟": { rank: 43018, meaning: "to bring up" },
  "تَأْسِرُ": { rank: 33026, meaning: "to take captive" },
  "تَؤُزُّ": { rank: 19083, meaning: "to incite" },
  "تَحَٰٓضُّ": { rank: 89018, meaning: "to feel the urge" },
  "يُصْهَرُ": { rank: 22020, meaning: "to melt" },
  "يُضَٰهِؤ": { rank: 9030, meaning: "to imitate" },
  "تَسَوَّرُ": { rank: 38021, meaning: "to climbe" },
  "تَسْتَبِينَ": { rank: 6055, meaning: "to manifest" },
  "يُجَاوِرُ": { rank: 33060, meaning: "to remain" },
  "يُجَنَّبُ": { rank: 92017, meaning: "to remove" },
  "تَسْتَأْنِسُ": { rank: 24027, meaning: "to ask permission" },
  "يُجْبَىٰٓ": { rank: 28057, meaning: "to bring" },
  "تَسُرُّ": { rank: 2069, meaning: "to please" },
  "عَرَّضْ": { rank: 2235, meaning: "to hint" },
  "تَحُسُّ": { rank: 3152, meaning: "to feel" },
  "تَزْدَرِىٓ": { rank: 11031, meaning: "to look down upon" },
  "تَزَيَّلُ": { rank: 48025, meaning: "to be apart" },
  "تَزَوَّدُ": { rank: 2197, meaning: "to take provision" },
  "مَرِضْ": { rank: 26080, meaning: "to be ill" },
  "تَرْقَىٰ": { rank: 17093, meaning: "to ascend" },
  "تَرْدَىٰ": { rank: 20016, meaning: "to perish" },
  "تَسْتَتِرُ": { rank: 41022, meaning: "to cover oneself" },
  "يُبْلِسُ": { rank: 30012, meaning: "to despair" },
  "تَسْتَرْضِعُ": { rank: 2233, meaning: "to be breastfed" },
  "تَسْتَقْسِمُ": { rank: 5003, meaning: "to seek division" },
  "تَسْرَحُ": { rank: 16006, meaning: "to take out" },
  "تَشِيعَ": { rank: 24019, meaning: "to spread" },
  "يُبِينُ": { rank: 43052, meaning: "to clear" },
  "يُبَطِّئَ": { rank: 4072, meaning: "to lag behind" },
  "يُبَصَّرُ": { rank: 70011, meaning: "to make (someone) see" },
  "يُبَتِّكُ": { rank: 4119, meaning: "to surely cut off" },
  "يُؤْلُ": { rank: 2226, meaning: "oto swear" },
  "يُؤْثَرُ": { rank: 74024, meaning: "to imitate" },
  "تَشْتَكِىٓ": { rank: 58001, meaning: "to direct the complaints" },
  "تَشْخَصُ": { rank: 14042, meaning: "to stare" },
  "يَهْجَعُ": { rank: 51017, meaning: "to sleep" },
  "تَصَدَّىٰ": { rank: 80006, meaning: "to give attention" },
  "يَهِيمُ": { rank: 26225, meaning: "to roam" },
  "يُحْفِ": { rank: 47037, meaning: "to press" },
  "يُحْمَدُ": { rank: 3188, meaning: "to praise" },
  "يُحْمَىٰ": { rank: 9035, meaning: "to be heated" },
  "تَخُطُّ": { rank: 29048, meaning: "to write it" },
  "يُضَيِّفُ": { rank: 18077, meaning: "to offer them hospitality" },
  "تَحِيدُ": { rank: 50019, meaning: "to avoid" },
  "بَرِقَ": { rank: 75007, meaning: "to dazzle" },
  "يُصْدِرَ": { rank: 28023, meaning: "to take away" },
  "يُصْحَبُ": { rank: 21043, meaning: "to protected" },
  "تَحْرُثُ": { rank: 56063, meaning: "to sow" },
  "يُصَدَّعُ": { rank: 56019, meaning: "to get headache" },
  "تَحْلِقُ": { rank: 2196, meaning: "to shave" },
  "يُسْمِنُ": { rank: 88007, meaning: "to nourish" },
  "يُسْحِتَ": { rank: 20061, meaning: "to destroy you" },
  "تَحْنَثْ": { rank: 38044, meaning: "to break oath" },
  "تَخَلَّتْ": { rank: 84004, meaning: "to become empty" },
  "يُسْجَرُ": { rank: 40072, meaning: "to kindle" },
  "يُسِيغُ": { rank: 14017, meaning: "to swallow" },
  "يُزْلِقُ": { rank: 68051, meaning: "to make it slip" },
  "مَرَدُ": { rank: 9101, meaning: "to persist" },
  "تَخْضَعْ": { rank: 33032, meaning: "to be soft" },
  "تَدَايَن": { rank: 2282, meaning: "to contract with one another" },
  "يُرْضِعْ": { rank: 2233, meaning: "to suckle" },
  "تَدَلَّىٰ": { rank: 53008, meaning: "to come down" },
  "تَدُورُ": { rank: 33019, meaning: "to resolve" },
  "تَدَّخِرُ": { rank: 3049, meaning: "to store" },
  "تَذُودَ": { rank: 28023, meaning: "to keep back" },
  "تَذْرُو": { rank: 18045, meaning: "to scatter" },
  "يُدَٰفِعُ": { rank: 22038, meaning: "to defend" },
  "تَذْهَلُ": { rank: 22002, meaning: "to forget" },
  "عَزَلْ": { rank: 33051, meaning: "to set aside" },
  "يُخْرِبُ": { rank: 59002, meaning: "to destroy" },
  "تَرَدَّىٰٓ": { rank: 92011, meaning: "to fall" },
  "يُخَيَّلُ": { rank: 20066, meaning: "to seem" },
  "ٱجْتُثَّتْ": { rank: 14026, meaning: "to uproot" },
  "أُعِيذُ": { rank: 3036, meaning: "to seek refuge" },
  "ٱجْنُبْ": { rank: 14035, meaning: "to keep away" },
  "أَسْتَخْلِصْ": { rank: 12054, meaning: "to select" },
  "أَرْسَىٰ": { rank: 79032, meaning: "to make firm" },
  "ٱقْتَدِهْ": { rank: 6090, meaning: "to follow" },
  "ٱقْتَحَمَ": { rank: 90011, meaning: "to attempt" },
  "فُزِّعَ": { rank: 34023, meaning: "to remove fear" },
  "فُرِجَتْ": { rank: 77009, meaning: "to separate" },
  "أَزَلَّ": { rank: 2036, meaning: "to stumble" },
  "أَزِفَتِ": { rank: 53057, meaning: "to approach" },
  "ٱغْسِلُ": { rank: 5006, meaning: "to wash" },
  "ٱغْتَرَفَ": { rank: 2249, meaning: "to take" },
  "ٱعْتِلُ": { rank: 44047, meaning: "to drag" },
  "ٱعْتَمَرَ": { rank: 2158, meaning: "to perform Umrah" },
  "أَسَلْ": { rank: 34012, meaning: "to cause to flow" },
  "أَسْبَغَ": { rank: 31020, meaning: "to amply bestow" },
  "ٱعْتَرَىٰ": { rank: 11054, meaning: "to seize" },
  "أَسْخَطَ": { rank: 47028, meaning: "to anger" },
  "ٱقْصِدْ": { rank: 31019, meaning: "to be moderate" },
  "ٱعْتَبِرُ": { rank: 59002, meaning: "to take a lesson" },
  "أَسْفَرَ": { rank: 74034, meaning: "to brighten" },
  "ٱطْرَحُ": { rank: 12009, meaning: "to cast" },
  "فَهَّمْ": { rank: 21079, meaning: "to make understand" },
  "أَشَارَتْ": { rank: 19029, meaning: "to point" },
  "أَشْرَقَتِ": { rank: 39069, meaning: "to shine" },
  "ٱصْطَنَعْ": { rank: 20041, meaning: "to choose" },
  "فَكَّرَ": { rank: 74018, meaning: "to think" },
  "أَشْكُوا۟": { rank: 12086, meaning: "to complain" },
  "ٱصْطَادُ": { rank: 5002, meaning: "to hunt" },
  "ٱصْدَعْ": { rank: 15094, meaning: "to proclaim" },
  "ٱشْمَأَزَّتْ": { rank: 39045, meaning: "to shrink with aversion" },
  "أَصَمَّ": { rank: 47023, meaning: "to make one deaf" },
  "أَصْبُ": { rank: 12033, meaning: "to incline" },
  "كَرَّهَ": { rank: 49007, meaning: "to make hateful" },
  "أَذَاعُ": { rank: 4083, meaning: "to spread" },
  "ٱشْتَدَّتْ": { rank: 14018, meaning: "to blow furiously" },
  "أَتْقَنَ": { rank: 27088, meaning: "to perfect" },
  "أَبَقَ": { rank: 37140, meaning: "to run away" },
  "أَبْرَمُ": { rank: 43079, meaning: "to determine" },
  "ٱنۢبَعَثَ": { rank: 91012, meaning: "to send forth" },
  "ٱنۢبَجَسَتْ": { rank: 7160, meaning: "to gushed forth" },
  "ٱنْهَارَ": { rank: 9109, meaning: "to collapse" },
  "ٱنْحَرْ": { rank: 108002, meaning: "to sacrifice" },
  "ٱنكَدَرَتْ": { rank: 81002, meaning: "to lose luster" },
  "أَبْشِرُ": { rank: 41030, meaning: "to receive the glad tidings" },
  "ٱنفَلَقَ": { rank: 26063, meaning: "to part" },
  "ٱنفَطَرَتْ": { rank: 82001, meaning: "to be cleft" },
  "أَبْكَىٰ": { rank: 53043, meaning: "to makes one weep" },
  "ٱنفَجَرَتْ": { rank: 2060, meaning: "to gushed forth" },
  "أَتَوَكَّؤُا۟": { rank: 20018, meaning: "to lean" },
  "ٱنصَرَفُ": { rank: 9127, meaning: "to turn away" },
  "أَثْقَلَت": { rank: 7189, meaning: "to grows heavy" },
  "ٱكْتَتَبَ": { rank: 25005, meaning: "to be written" },
  "قَلَّ": { rank: 4007, meaning: "to be little" },
  "قَلَىٰ": { rank: 93003, meaning: "to be displeased" },
  "أَجْلِبْ": { rank: 17064, meaning: "to assault" },
  "ٱنتَثَرَتْ": { rank: 82002, meaning: "to scatter" },
  "أَحْتَنِكَ": { rank: 17062, meaning: "to surely destroy" },
  "كَثَّرَ": { rank: 7086, meaning: "to increase" },
  "ٱمْتَٰزُ": { rank: 36059, meaning: "to stand apart" },
  "ٱمْتَلَأْ": { rank: 50030, meaning: "to fill" },
  "قَصَمْ": { rank: 21011, meaning: "to shatter" },
  "ٱلْغَ": { rank: 41026, meaning: "to make noise" },
  "ٱلْتَمِسُ": { rank: 57013, meaning: "to seek" },
  "ٱلْتَقَمَ": { rank: 37142, meaning: "to swallow" },
  "ٱلْتَفَّتِ": { rank: 75029, meaning: "to fabricate" },
  "قَاسَمَ": { rank: 7021, meaning: "to swear" },
  "ٱشْتَعَلَ": { rank: 19004, meaning: "to flare" },
  "أَضْحَكَ": { rank: 53043, meaning: "to make one laugh" },
  "ٱحْتَرَقَتْ": { rank: 2266, meaning: "to be burnt" },
  "أَوْرَدَ": { rank: 11098, meaning: "to lead them" },
  "أَمْكَنَ": { rank: 8071, meaning: "to gave power" },
  "أَمْهِلْ": { rank: 86017, meaning: "to give respite" },
  "ٱسْتَزَلَّ": { rank: 3155, meaning: "to make them slip" },
  "ٱسْتَرْهَبُ": { rank: 7116, meaning: "to terrify them" },
  "ٱسْتَرَقَ": { rank: 15018, meaning: "to steal" },
  "فَارِقُ": { rank: 65002, meaning: "to part with them" },
  "أَنقَضَ": { rank: 94003, meaning: "to weigh upon" },
  "أَهَمَّتْ": { rank: 3154, meaning: "to worry" },
  "كُبَّتْ": { rank: 27090, meaning: "to be cast down" },
  "أَهُشُّ": { rank: 20018, meaning: "to bring down leaves" },
  "ٱسْتَجَارَ": { rank: 9006, meaning: "to seek your protection" },
  "أَوِّبِ": { rank: 34010, meaning: "to repeat praises" },
  "أَوْجَفْ": { rank: 59006, meaning: "to make expedition" },
  "ٱزْدُجِرَ": { rank: 54009, meaning: "to repell" },
  "ٱزَّيَّنَتْ": { rank: 10024, meaning: "to be beautified" },
  "أَلَتْ": { rank: 52021, meaning: "to deprive" },
  "كُبْكِبُ": { rank: 26094, meaning: "to overturn" },
  "أَوْضَعُ": { rank: 9047, meaning: "to be active" },
  "كُشِطَتْ": { rank: 81011, meaning: "to strip away" },
  "ٱدَّٰرَْٰٔ": { rank: 2072, meaning: "to be disputed" },
  "غَلَّقَتِ": { rank: 12023, meaning: "to close" },
  "ٱدَّكَرَ": { rank: 12045, meaning: "to remember" },
  "ٱخْلَعْ": { rank: 20012, meaning: "to remove" },
  "ٱخْسَؤ": { rank: 23108, meaning: "to remain despised" },
  "أُشْرِبُ": { rank: 2093, meaning: "to drink" },
  "مَسَخْ": { rank: 36067, meaning: "to transform" },
  "أُفَوِّضُ": { rank: 40044, meaning: "to entrust" },
  "أُقِّتَتْ": { rank: 77011, meaning: "to gather" },
  "آزَرَ": { rank: 48029, meaning: "to strengthen" },
  "أَلْهَمَ": { rank: 91008, meaning: "to inspire" },
  "ٱسْتَطْعَمَ": { rank: 18077, meaning: "to ask for food" },
  "أَطْغَيْ": { rank: 50027, meaning: "to transgress" },
  "أَفَاقَ": { rank: 7143, meaning: "to recover" },
  "ٱسْتُحْفِظُ": { rank: 5044, meaning: "to entrust" },
  "أَظْفَرَ": { rank: 48024, meaning: "to give victory" },
  "أَظْلَمَ": { rank: 2020, meaning: "to darken" },
  "فَرَشْ": { rank: 51048, meaning: "to spread" },
  "أَعِيبَ": { rank: 18079, meaning: "to cause defect" },
  "أَعْثَرْ": { rank: 18021, meaning: "to make known" },
  "ٱسْتَوْقَدَ": { rank: 2017, meaning: "to kindle" },
  "أَعْجَلَ": { rank: 20083, meaning: "to make one hasten" },
  "ٱسْتَهْوَتْ": { rank: 6071, meaning: "to entice" },
  "أَعْقَبَ": { rank: 9077, meaning: "to penalize" },
  "أَعْنَتَ": { rank: 2220, meaning: "to put in difficulties" },
  "فَدَيْ": { rank: 37107, meaning: "to ransom" },
  "أَغْطَشَ": { rank: 79029, meaning: "to darken" },
  "أَغْفَلْ": { rank: 18028, meaning: "to make heedless" },
  "أَفْضَىٰ": { rank: 4021, meaning: "to go" },
  "أَلَ": { rank: 34010, meaning: "to make pliable" },
  "أَقَلَّتْ": { rank: 7057, meaning: "to carry" },
  "أَقْبَرَ": { rank: 80021, meaning: "to bury" },
  "ٱسْتَقَرَّ": { rank: 7143, meaning: "to remain" },
  "أَقْلِعِ": { rank: 11044, meaning: "to withhold" },
  "أَكْبَرْ": { rank: 12031, meaning: "to admire" },
  "ٱسْتَغْلَظَ": { rank: 48029, meaning: "to become thick" },
  "كَفَّلَ": { rank: 3037, meaning: "to put in care" },
  "أَكْدَىٰٓ": { rank: 53034, meaning: "to withhold" },
  "أَكْفَرَ": { rank: 80017, meaning: "to be ungrateful" },
  "ٱسْتَعْمَرَ": { rank: 11061, meaning: "to settle you" },
  "ٱسْتَعْلَىٰ": { rank: 20064, meaning: "to overcome" },
  "ٱسْتَعْصَمَ": { rank: 12032, meaning: "to take refuge in" },
  "أَكْفِلْ": { rank: 38023, meaning: "to entrust" },
  "فَتَقْ": { rank: 21030, meaning: "to part" },
  "تَصِيرُ": { rank: 42053, meaning: "to reach" },
  "عَدَّدَ": { rank: 104002, meaning: "to count" },
  "يَنْعِقُ": { rank: 2171, meaning: "to shout" },
  "يَتَحَاكَمُ": { rank: 4060, meaning: "to go for judge" },
  "يَبْحَثُ": { rank: 5031, meaning: "to scratch" },
  "حَصْحَصَ": { rank: 12051, meaning: "to manifest" },
  "نَتَقْ": { rank: 7171, meaning: "to raise" },
  "حَصَد": { rank: 12047, meaning: "to reap" },
  "يَتَجَرَّعُ": { rank: 14017, meaning: "to sip" },
  "يَتَجَنَّبُ": { rank: 87011, meaning: "to avoid" },
  "يَتَحَآجُّ": { rank: 40047, meaning: "to dispute" },
  "وَكَزَ": { rank: 28015, meaning: "to struck with fist" },
  "يَتَخَبَّطُ": { rank: 2275, meaning: "to confound" },
  "نَتَجَاوَزُ": { rank: 46016, meaning: "to overlook" },
  "يَتَخَلَّفُ": { rank: 9120, meaning: "to remain behind" },
  "حَجَّ": { rank: 2158, meaning: "to perform Hajj" },
  "حَبَّبَ": { rank: 49007, meaning: "to endear" },
  "نَبْتَهِلْ": { rank: 3061, meaning: "to pray humbly" },
  "يَبِيتُ": { rank: 25064, meaning: "to spend a night" },
  "حَفَفْ": { rank: 18032, meaning: "to border" },
  "حُصِّلَ": { rank: 100010, meaning: "to make apparent" },
  "يَؤودُ": { rank: 2255, meaning: "to tire" },
  "يَأْنِ": { rank: 57016, meaning: "to be dear" },
  "يَأْلُ": { rank: 3118, meaning: "to spare" },
  "خَبَتْ": { rank: 17097, meaning: "to subside" },
  "خَبُثَ": { rank: 7058, meaning: "to be bad" },
  "يَأْتَلِ": { rank: 24022, meaning: "to swear" },
  "صَكَّتْ": { rank: 51029, meaning: "to struck" },
  "خَلَصُ": { rank: 12080, meaning: "to seclude" },
  "خَلَطُ": { rank: 9102, meaning: "to mix" },
  "خَلُّ": { rank: 9005, meaning: "to leave" },
  "خُلِّفُ": { rank: 9118, meaning: "to leave behind" },
  "دَحَىٰ": { rank: 79030, meaning: "to spread" },
  "دَسَّىٰ": { rank: 91010, meaning: "to bury" },
  "دَعْ": { rank: 33048, meaning: "to disregard" },
  "يَتَرَاجَعَ": { rank: 2230, meaning: "to return" },
  "يَتَرَدَّدُ": { rank: 9045, meaning: "to waver" },
  "يَتَسَلَّلُ": { rank: 24063, meaning: "to slip away" },
  "يَتَمَطَّىٰٓ": { rank: 75033, meaning: "to swagger" },
  "يَحُورَ": { rank: 84014, meaning: "to return" },
  "تُوعِدُ": { rank: 7086, meaning: "to threaten" },
  "تُوَقِّرُ": { rank: 48009, meaning: "to respect" },
  "تَّزَٰوَرُ": { rank: 18017, meaning: "to inclinine" },
  "يَجْمَحُ": { rank: 9057, meaning: "to run wild" },
  "تَّقْرِضُ": { rank: 18017, meaning: "to passing away" },
  "يَجُرُّ": { rank: 7150, meaning: "to drag" },
  "يَثْنُ": { rank: 11005, meaning: "to fold" },
  "يَتَّكِؤ": { rank: 43034, meaning: "to recline" },
  "يَتِيهُ": { rank: 5026, meaning: "to wander" },
  "يَتِرَ": { rank: 47035, meaning: "to deprive" },
  "يَتَنَاهَ": { rank: 5079, meaning: "to forbid" },
  "يَتَنَافَسِ": { rank: 83026, meaning: "to aspire" },
  "ثَبَّطَ": { rank: 9046, meaning: "to lag behind" },
  "ثُوِّبَ": { rank: 83036, meaning: "to reward" },
  "يَتَسَنَّهْ": { rank: 2259, meaning: "to change with time" },
  "يَتَلَٰوَمُ": { rank: 68030, meaning: "to blame" },
  "يَتَلَطَّفْ": { rank: 18019, meaning: "to be cautious" },
  "جَابُ": { rank: 89009, meaning: "to carve out" },
  "جَاسُ": { rank: 17005, meaning: "to enter" },
  "يَتَفَيَّؤُا۟": { rank: 16048, meaning: "to incline" },
  "جَرَحْ": { rank: 6060, meaning: "to commit" },
  "يَتَفَقَّهُ": { rank: 9122, meaning: "to understand" },
  "يَتَفَضَّلَ": { rank: 23024, meaning: "to assert superiority" },
  "يَتَفَجَّرُ": { rank: 2074, meaning: "gush forth" },
  "يَتَغَيَّرْ": { rank: 47015, meaning: "to change" },
  "يَتَغَامَزُ": { rank: 83030, meaning: "to wink" },
  "جَزِعْ": { rank: 14021, meaning: "to show intolerance" },
  "صَلُّ": { rank: 69031, meaning: "to burn him" },
  "جَنَّ": { rank: 6076, meaning: "to cover" },
  "دَمْدَمَ": { rank: 91014, meaning: "to destroy" },
  "نَخْزَىٰ": { rank: 20134, meaning: "to be disgraced" },
  "تَضَرَّعُ": { rank: 6043, meaning: "to be humble" },
  "سَلَقُ": { rank: 33019, meaning: "to smite" },
  "سُطِحَتْ": { rank: 88020, meaning: "to spread out" },
  "سُجِّرَتْ": { rank: 81006, meaning: "to make to overflow" },
  "نَٰجَيْ": { rank: 58012, meaning: "to privately consult" },
  "نُجَٰزِىٓ": { rank: 34017, meaning: "to recompense" },
  "نُدَاوِلُ": { rank: 3140, meaning: "to alternate" },
  "نَسْفَعًۢ": { rank: 96015, meaning: "to drag" },
  "سَكَتَ": { rank: 7154, meaning: "to be calm" },
  "وَقَبَ": { rank: 113003, meaning: "to spread" },
  "نُقَدِّسُ": { rank: 2030, meaning: "to sancify" },
  "نُقِرَ": { rank: 74008, meaning: "to blow" },
  "نُقْرِئُ": { rank: 87006, meaning: "to make you recite" },
  "نُكِسُ": { rank: 21065, meaning: "to be turned" },
  "نُنشِزُ": { rank: 2259, meaning: "to raise" },
  "نُنَكِّسْ": { rank: 36068, meaning: "to reverse" },
  "نَمِيرُ": { rank: 12065, meaning: "to get provision" },
  "نَكِّرُ": { rank: 27041, meaning: "to disguise" },
  "نَكِرَ": { rank: 11070, meaning: "to feel unfamiliar" },
  "سُعِدُ": { rank: 11108, meaning: "to be glad" },
  "سُعِّرَتْ": { rank: 81012, meaning: "to set ablaze" },
  "نَقْتَبِسْ": { rank: 57013, meaning: "to acquire" },
  "نَقَّبُ": { rank: 50036, meaning: "to explore" },
  "سُكِّرَتْ": { rank: 15015, meaning: "to dazzle" },
  "سِيحُ": { rank: 9002, meaning: "to roam" },
  "شَارِكْ": { rank: 17064, meaning: "to be a partner" },
  "شَاوِرْ": { rank: 3159, meaning: "to consult" },
  "نَفَشَتْ": { rank: 21078, meaning: "to pasture" },
  "شَجَرَ": { rank: 4065, meaning: "to arise" },
  "نَسْلَخُ": { rank: 36037, meaning: "to withdraw" },
  "نَعَّمَ": { rank: 89015, meaning: "to favor" },
  "نَطْوِى": { rank: 21104, meaning: "to fold" },
  "نَضِجَتْ": { rank: 4056, meaning: "to roaste" },
  "سَفِهَ": { rank: 2130, meaning: "to fool" },
  "نَّبْرَأَ": { rank: 57022, meaning: "to bring into existence" },
  "نَّذِلَّ": { rank: 20134, meaning: "to humiliate" },
  "رُجَّتِ": { rank: 56004, meaning: "to be shaken" },
  "ذَكَّيْ": { rank: 5003, meaning: "to slaughter" },
  "رَابِطُ": { rank: 3200, meaning: "to be constant" },
  "رَانَ": { rank: 83014, meaning: "to covere" },
  "رَبِحَت": { rank: 2016, meaning: "to profit" },
  "وَصَّلْ": { rank: 28051, meaning: "to convey" },
  "صَبَّحَ": { rank: 54038, meaning: "to greet in the morning" },
  "صَابِرُ": { rank: 3200, meaning: "to be patient" },
  "وَسَقَ": { rank: 84017, meaning: "to envelop" },
  "وَسَطْ": { rank: 100005, meaning: "to penetrate" },
  "شُبِّهَ": { rank: 4157, meaning: "to make to appear" },
  "رَدِفَ": { rank: 27072, meaning: "to close behind" },
  "وَدَّعَ": { rank: 93003, meaning: "to forsake" },
  "نَسِمُ": { rank: 68016, meaning: "to brand" },
  "رَكَّبَ": { rank: 82008, meaning: "to assemble" },
  "وَجَبَتْ": { rank: 22036, meaning: "to be down" },
  "نَسْتَنسِخُ": { rank: 45029, meaning: "to transcribe" },
  "وَاثَقَ": { rank: 5007, meaning: "to be bound" },
  "هُزِّ": { rank: 19025, meaning: "to shake" },
  "هُدِّمَتْ": { rank: 22040, meaning: "to demolish" },
  "هَيْتَ": { rank: 12023, meaning: "to come on" },
  "زَكَىٰ": { rank: 24021, meaning: "to be pure" },
  "شَغَلَتْ": { rank: 48011, meaning: "to keep busy" },
  "زَيَّلْ": { rank: 10028, meaning: "to be separate" },
  "زُحْزِحَ": { rank: 3185, meaning: "to draw away" },
  "زُرْ": { rank: 102002, meaning: "to visit" },
  "سَابِقُ": { rank: 57021, meaning: "to race" },
  "سَالَتْ": { rank: 13017, meaning: "to flow" },
  "سَاهَمَ": { rank: 37141, meaning: "to join" },
  "سَاوَىٰ": { rank: 18096, meaning: "to level" },
  "سَجَىٰ": { rank: 93002, meaning: "to covers with darkness" },
  "يَحِضْ": { rank: 65004, meaning: "to menstruate" },
  "يَحِيفَ": { rank: 24050, meaning: "to be unjust" },
  "تُورُ": { rank: 56071, meaning: "to ignite" },
  "يَعْشُ": { rank: 43036, meaning: "to turn away" },
  "يَعْبَؤُا۟": { rank: 25077, meaning: "to care" },
  "تَقْصُرُ": { rank: 4101, meaning: "to shorten" },
  "تَقْشَعِرُّ": { rank: 39023, meaning: "to shiver" },
  "طَوَّعَتْ": { rank: 5030, meaning: "to prompt" },
  "مَهَّد": { rank: 74014, meaning: "to spread" },
  "كَاتِبُ": { rank: 24033, meaning: "to give in writing" },
  "تَفْضَحُ": { rank: 15068, meaning: "to shame" },
  "تُمْسُ": { rank: 30017, meaning: "to reach the evening" },
  "يَعْكُفُ": { rank: 7138, meaning: "to devote" },
  "تَفْتَؤُا۟": { rank: 12085, meaning: "to not cease" },
  "عَادَيْ": { rank: 60007, meaning: "to have enemies" },
  "يَغُوصُ": { rank: 21082, meaning: "to dive" },
  "تَفَكَّهُ": { rank: 56065, meaning: "to wonder" },
  "يَغْتَب": { rank: 49012, meaning: "to backbite" },
  "يَطْهُرْ": { rank: 2222, meaning: "to cleanse" },
  "تَقْفُ": { rank: 17036, meaning: "to pursue" },
  "تَقْهَرْ": { rank: 93009, meaning: "to oppress" },
  "يَطْلُبُ": { rank: 7054, meaning: "to seek" },
  "تَلَذُّ": { rank: 43071, meaning: "to delight" },
  "يَطِيرُ": { rank: 6038, meaning: "to fly" },
  "تَلَظَّىٰ": { rank: 92014, meaning: "to blaze" },
  "تَلَهَّىٰ": { rank: 80010, meaning: "to be distracted" },
  "تَلَّ": { rank: 37103, meaning: "to put down" },
  "تَلْفَحُ": { rank: 23104, meaning: "to burn" },
  "يَصْعَدُ": { rank: 35010, meaning: "to ascend" },
  "يَصْطَرِخُ": { rank: 35037, meaning: "to cry" },
  "يَصْرِمُ": { rank: 68017, meaning: "to pluck" },
  "يَصْدُرُ": { rank: 99006, meaning: "to proceed" },
  "يَصَّعَّدُ": { rank: 6125, meaning: "to climb" },
  "يَصَّدَّعُ": { rank: 30043, meaning: "to be divided" },
  "تَلْفِتَ": { rank: 10078, meaning: "to turn away" },
  "يَغْلِى": { rank: 44045, meaning: "to boil" },
  "يَفْتَرِي": { rank: 60012, meaning: "to invent" },
  "يَفْتُرُ": { rank: 21020, meaning: "to slack" },
  "يَلْفِظُ": { rank: 50018, meaning: "to utter" },
  "تَضْحَىٰ": { rank: 20119, meaning: "to be exposed to the sun's heat" },
  "يَنقَضَّ": { rank: 18077, meaning: "to collapse" },
  "تَطَاوَلَ": { rank: 28045, meaning: "to prolonged" },
  "شَرِّدْ": { rank: 8057, meaning: "to disperse" },
  "عَجَزْ": { rank: 5031, meaning: "to be unable" },
  "تَظْمَؤُا۟": { rank: 20119, meaning: "to suffer from thirst" },
  "يَمْهَدُ": { rank: 30044, meaning: "to prepare" },
  "تَعَاسَرْ": { rank: 65006, meaning: "to disagree" },
  "تَعَاطَىٰ": { rank: 54029, meaning: "to take" },
  "عَبَّد": { rank: 26022, meaning: "to enslave" },
  "تَعَجَّلَ": { rank: 2203, meaning: "to hurry" },
  "يَمُوجُ": { rank: 18099, meaning: "to surge" },
  "تَعَمَّدَتْ": { rank: 33005, meaning: "to intend" },
  "تَعُولُ": { rank: 4003, meaning: "to oppress" },
  "تَعِيَ": { rank: 69012, meaning: "to be conscious" },
  "تَفَقَّدَ": { rank: 27020, meaning: "to inspect" },
  "تَعْبَثُ": { rank: 26128, meaning: "to amuse" },
  "تَعْبُرُ": { rank: 12043, meaning: "to interpret" },
  "تَعْتَدُّ": { rank: 33049, meaning: "to count" },
  "تَعْرَىٰ": { rank: 20118, meaning: "to be unclothed" },
  "يَلِتْ": { rank: 49014, meaning: "to deprive" },
  "يَلُ": { rank: 9123, meaning: "to be close" },
  "يَكْلَؤُ": { rank: 21042, meaning: "to protect" },
  "تَغَشَّىٰ": { rank: 7189, meaning: "to covers" },
  "تَغْتَسِلُ": { rank: 4043, meaning: "to bathe" },
  "يَقْتُرُ": { rank: 25067, meaning: "to not be stingy" },
  "تَغْفُلُ": { rank: 4102, meaning: "to neglect" },
  "عَاشِرُ": { rank: 4019, meaning: "to live with" },
  "تَفَسَّحُ": { rank: 58011, meaning: "to make room" },
  "يَفْرُطَ": { rank: 20045, meaning: "to hasten" },
  "تَمَثَّلَ": { rank: 19017, meaning: "to embody" },
  "تَمَيَّزُ": { rank: 67008, meaning: "to burst" },
  "يَشْوِى": { rank: 18029, meaning: "to roast" },
  "تُصَعِّرْ": { rank: 31018, meaning: "to turn" },
  "تُدِيرُ": { rank: 2282, meaning: "to carry out" },
  "تُذِلُّ": { rank: 3026, meaning: "to humiliate" },
  "تُرِيحُ": { rank: 16006, meaning: "to bring them in" },
  "يَرْكُمَ": { rank: 8037, meaning: "to heap" },
  "تُرْهِبُ": { rank: 8060, meaning: "to terrify" },
  "تُسَوَّىٰ": { rank: 4042, meaning: "to level" },
  "تُسَٰقِطْ": { rank: 19025, meaning: "to drop" },
  "تُسِيمُ": { rank: 16010, meaning: "to pasture the cattle" },
  "يَرْشُدُ": { rank: 2186, meaning: "to be led aright" },
  "تُشْطِطْ": { rank: 38022, meaning: "to be unjust" },
  "يَرْتَقُ": { rank: 38010, meaning: "to let them ascend" },
  "يَرْتَعْ": { rank: 12012, meaning: "to enjoy" },
  "تُشْمِتْ": { rank: 7150, meaning: "to rejoice" },
  "يَدْمَغُ": { rank: 21018, meaning: "to breaks the head" },
  "صُدُّ": { rank: 13033, meaning: "to be hindered" },
  "تُخَالِطُ": { rank: 2220, meaning: "to associate" },
  "يَدِينُ": { rank: 9029, meaning: "to acknowledge" },
  "تُصْعِدُ": { rank: 3153, meaning: "to run uphill" },
  "يَدُسُّ": { rank: 16059, meaning: "to bury" },
  "تُضَيِّقُ": { rank: 65006, meaning: "to distress" },
  "تُعِزُّ": { rank: 3026, meaning: "to honor" },
  "تُغْمِضُ": { rank: 2267, meaning: "to close one or both eyes" },
  "تُفَتَّحُ": { rank: 7040, meaning: "to open" },
  "يَخْذُلْ": { rank: 3160, meaning: "to forsake" },
  "تُفَنِّدُ": { rank: 12094, meaning: "to disprove" },
  "تُفَٰدُ": { rank: 2085, meaning: "to ransom" },
  "تُقْلَبُ": { rank: 29021, meaning: "to return" },
  "يَحْطِمَ": { rank: 27018, meaning: "to crush" },
  "تُكْوَىٰ": { rank: 9035, meaning: "to be branded" },
  "تُمَارِ": { rank: 18022, meaning: "to argue" },
  "يَزِفُّ": { rank: 37094, meaning: "to haste" },
  "تُخَافِتْ": { rank: 17110, meaning: "to be silent" },
  "تَمْرَحُ": { rank: 40075, meaning: "to be insolent" },
  "تَنِيَ": { rank: 20042, meaning: "to slacken" },
  "تَنَابَزُ": { rank: 49011, meaning: "to call each other" },
  "تَنَادَ": { rank: 68021, meaning: "to call each other" },
  "تَنَاصَرُ": { rank: 37025, meaning: "to help one another" },
  "يَسْلُبْ": { rank: 22073, meaning: "to snatch away" },
  "تَنَفَّسَ": { rank: 81018, meaning: "to breathe" },
  "يَسْطُرُ": { rank: 68001, meaning: "to write" },
  "يَسْطُ": { rank: 22072, meaning: "to attack" },
  "يَسْرِ": { rank: 89004, meaning: "to pass" },
  "يَسْتَوْفُ": { rank: 83002, meaning: "to take in full" },
  "يَسْتَنۢبِطُ": { rank: 4083, meaning: "to draw correct conclusion" },
  "يَسْتَنۢبِؤ": { rank: 10053, meaning: "to inform" },
  "يَسْتَنكِحَ": { rank: 33050, meaning: "to marry" },
  "يَسْتَنقِذُ": { rank: 22073, meaning: "to take back" },
  "تَنُوٓأُ": { rank: 28076, meaning: "to burden" },
  "طَعَنُ": { rank: 9012, meaning: "to defame" },
  "تُحَرِّكْ": { rank: 75016, meaning: "to move" },
  "تَنۢبُتُ": { rank: 23020, meaning: "to produce" },
  "تَهَجَّدْ": { rank: 17079, meaning: "to arise from sleep for prayer" },
  "يَسْتَصْرِخُ": { rank: 28018, meaning: "to cry out for help" },
  "يَسْتَسْخِرُ": { rank: 37014, meaning: "to mock" },
  "طَحَىٰ": { rank: 91006, meaning: "to spread" },
  "تَوَاعَد": { rank: 8042, meaning: "to make an appointment" },
  "يَسْتَحْسِرُ": { rank: 21019, meaning: "to tire" },
  "يَسْتَثْنُ": { rank: 68018, meaning: "to make exception" },
  "تَوَجَّهَ": { rank: 28022, meaning: "to turn the face" },
  "تُبَذِّرْ": { rank: 17026, meaning: "to spend" },
  "يَسْبِتُ": { rank: 7163, meaning: "to be quiet" },
  "صُرْ": { rank: 2260, meaning: "to incline" },
  "يَسَّمَّعُ": { rank: 37008, meaning: "to listen" },
  "تُبْقِى": { rank: 74028, meaning: "to remain" },
  "تَقَاسَمُ": { rank: 27049, meaning: "to swear to each other" },
};