export const MSG = {
  IFRAME_READY: 'IFRAME_READY',
  UPDATE_SETTING: 'UPDATE_SETTING',
  SAVE_PROGRESS: 'SAVE_PROGRESS',
  SAVE_PROGRESS_SUCCESS: 'SAVE_PROGRESS_SUCCESS',
  SAVE_PROGRESS_FAILED: 'SAVE_PROGRESS_FAILED',
  WORD_DETAILS_OPENED: 'WORD_DETAILS_OPENED',
  WORD_DETAILS_CLOSED: 'WORD_DETAILS_CLOSED',
  QQ_SWIPE: 'QQ_SWIPE'
};
